### ISSUE TITLE
Fix "More atoms break away" alert

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#102]
As of writing this issue, the "more" break away alert often happens before the first break away alert. Here is what we want the end product to look like:

* The first time that atoms break away, we hear the specific "first time" alert.
* create a metric for determining the difference between "break away events"
* each additional "break away event", alert the "more atoms break away" alert
* reset will reset this system, such that then the "first time" alert will alert again on first evaporation.

Tagging @terracoda for comment.

**Comment by terracoda** [comment]
@zepumph, this is a good description of the issue, and it seems to have already been fixed.

**Comment by terracoda** [comment]
@zepumph, I hear the break away alerts in the correct order all the time now! Thanks!
