### ISSUE TITLE
Please port latest description to sonified version 

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#105]
Please port the sim to the sonified version once all the issues that have to do with alerts are completed. Specifically these are:
- [x] #99 
- [x] #100  
- [x] #101  
- [x] #102 
- [x] #103
- [x] #104  
- [x] #111  
- [x] #112 (not a show stopper)
- [x] #116 (at least the left and right edge bounds, would be nice)

**Comment by zepumph** [comment]
As of this morning, all of the above issues are closed. I will double check at the friction meeting today to make sure that there aren't any other tweaks to add into the sonification version.

**Comment by terracoda** [comment]
Sorry @zepumph, I forgot about this issue. I think it might be good to add the directional and orientation alerts (edges of rubbing area) first.

**Comment by terracoda** [comment]
@zepumph, I added 4 more issues to the list. If any of these will take you beyond the week of the 17th, we may want to port changes over regardless. The next round of interviews are being lined up for the week of 17th.

**Comment by zepumph** [comment]
I want to make sure that you also have time to listen with sonification and provide feedback before leaving. When is the latest I could get you a new link for you to have time for feedback?

**Comment by terracoda** [comment]
@zepumph, if you have a nice version that includes up to issue #112 perhpas we could use that for interviews tomorrow and later this week?

Alternatively, if there is a nice version without the up-down and left-right alerts, and only the bounds implemented that would also be nice.

Once ported I can make sure version do not contain any of the latest bugs #120 ,#121, #122 that I just found (sorry).

**Comment by zepumph** [comment]
See https://github.com/phetsims/friction/issues/123. Closing
