### ISSUE TITLE
Add query parameters to adjust constants

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#106]
From discussion with @terracoda today. As we implement hard coded thresholds and heuristics, it will be good to implement query parameters to set the values. This way @terracoda as the designer will have better control about the alert flow by finding the perfect value combinations herself. I'll edit the list as I think about it:

- [ ]  Decreasing: AMPLITUDE_DECREASING_THRESHOLD
- [ ] Decreasing: 1 or 2 "jiggling less now cooler" strings before hearing "even less/even cooler"
- [ ] Decreasing: ALERT_TIME_DELAY (time between alerts)
- [ ] Increasing: DRAG_SESSION_THRESHOLD
- [ ] Increasing: ALERT_TIME_DELAY
- [ ] break away: ALERT_TIME_DELAY

**Comment by zepumph** [comment]
@terracoda I implemented this above. Please have a look at at the following url, which has a lot in there:

http://phettest.colorado.edu/friction/friction_a11y_view.html?brand=phet&ea&amplitudeDecreasingThreshold=1&oneJigglingLessNowCoolerAlerts&coolingAlertTimeDelay=3000&warmingAlertTimeDelay=500&dragSessionThreshold=1000&breakAwayAlertTimeDelay=2000

Each parameter is manually set to it's default (redundantly, because you can omit the query parameter to get it's default value/behavior also). This is to help you make tweaks a bit easier.

Please see https://github.com/phetsims/friction/blob/master/js/friction/FrictionQueryParameters.js for documentation on each of the query parameters, though I tried to name them as descriptively as possible.

**Comment by terracoda** [comment]
@zepumph, awesome, I'll try this out in my morning, not sure why I did not see this commit earlier.

**Comment by terracoda** [comment]
@zepumph, the defaults are pretty good.

I shortened the warningAlertTimeDelay to 250:
http://phettest.colorado.edu/friction/friction_en.html?brand=phet&ea&amplitudeDecreasingThreshold=1&oneJigglingLessNowCoolerAlerts&coolingAlertTimeDelay=3000&warmingAlertTimeDelay=250&dragSessionThreshold=1000&breakAwayAlertTimeDelay=2000

I'd like to play with this a little more.

**Comment by terracoda** [comment]
The only alert that might need some further tweaking is the "very hot" one that fires at the evaporation point. Is there a parameter for that one?

**Comment by zepumph** [comment]
Ha! Great minds think alike:

![image](https://user-images.githubusercontent.com/6856943/45384112-8b925380-b5b9-11e8-8c95-9542e77e1803.png)


In my mind this "further tweaking" would be adjusting the temp/amplitude when we could alert the "very hot" alerts. Right now it is the evaporation limit, but we can tweak a number that is "X" hotter than evaporation before you have the potential to hear the "very hot" alerts. 

The reason why I say "potential" is because the "very hot" alerts still exist in the same system as the "warmer/hotter" alerts in the sense that you have to wait "warmingAlertTimeDelay" between alerts. This applies to the "warmer", "hotter", "even hotter", and "very hot" alerts. (sorry if that isn't clear). I'm happy to discuss in person if this still is confusing.

Please let me know if this "tweaking value" makes sense, or if you would rather have another one.

**Comment by terracoda** [comment]
@zepumph, so at the moment, I'll get a break away alert at the evaporation point, or else (if there are no more atoms to break away), I'll get a the alertMaxTemp? Or maybe you ar esaying that the warmer hotter alerts are in a separate system than the break away alerts.

I'll review the alerts and see when I want them to fire and then we can see what system the alertMaxTemp should go.

My gut is that maybe we need something more "comparative in nature" for the the warmer-hotter system. Like maybe, "Even faster, even hotter", "Even faster, still hotter."

**Comment by terracoda** [comment]
@zepumph, I made a small change to the end of the increasing alerts and this might do the trick. I Added changes in red in the design document, but basically things would go like this in terms of continuous warming:

1. On focus: "Atoms jiggle a tiny bit, temperature cool."
2. Start of friction: "Jiggling more, warmer."
3. Continue friction: "Jiggling faster, now hotter."
4. Continued increased friction: "Jiggling even faster, even hotter."
5. 1st evaporation point reached: "Very hot. Atoms break away from chemistry book." 
6. Subsequent evaporation points until no more atoms available to evaporate: "Very hot. More atoms break away."
7. **NEW** Evaporation point and no atoms left to evaporate: "Very hot. Atoms jiggling very fast."
8. **NEW** Beyond evaporation point: 
  a. "Jiggling even faster, now hotter." or 
  b. "Jiggling super fast, temperature super hot." or 
  c. "Jiggling super fast, super hot."
9. Interaction hint to reset after 3 #8 alerts: "Reset the sim to make more observations."

For the #8 alert, I think I would like to try 8b as is reinforces the idea of a thermometer being present.

The #8 replaces the current alert of “Atoms very fast, still very hot.” I am not sure what system it should be in until I talk to you.

**Comment by zepumph** [comment]
anything modular and straightforward like that to me deserves its own issue.

**Comment by zepumph** [comment]
I don't see an issue linked to this issue, back to @terracoda to finish this one off.

**Comment by terracoda** [comment]
Oh sorry, @zepumph, I'll make some new issues for you ;-)

**Comment by terracoda** [comment]
@zepumph, I won't get to this today, sorry. First thing tomorrow.

**Comment by terracoda** [comment]
Marking as top priority for myself!

**Comment by terracoda** [comment]
@zepumph, ok moved https://github.com/phetsims/friction/issues/106#issuecomment-420728699 to #119. Apologies that took so long.

**Comment by terracoda** [comment]
@zepumph, I've copied the handy query parameters to the design document, so I guess we can close this issue, unless you need it?

Assigning back to you for closing.

**Comment by zepumph** [comment]
I think the best way to proceed with this issue, is to see how other issues go, and then revisit these parameters. Once (a) other issues have solidified and (b) you have found good numbers from the parameters, then we can put them directly into the sim as new defaults so that we won't always need the query parameters. Marking on-hold until things like #119 and #116 are done.

**Comment by zepumph** [comment]
@terracoda how do you feel about these alerts these days? Do they need more tweaking?

**Comment by zepumph** [comment]
@terracoda these parameters have not changed for a long time (over 2 months). Is anything else needed here?

**Comment by terracoda** [comment]
@zepumph, the sim started sounding really good after you implemented these parameters and I haven't really played with them except very early on.

If you need to remove them, it is likely safe to do so.

**Comment by zepumph** [comment]
Sounds good, I'll take care of this.
