### ISSUE TITLE
increasing/decreasing alerts should work with mouse drag

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#107]
So far I have only been implementing/testing these alerts with keyboard, but they should work with mouse too. I have implemented them such that it shouldn't be too difficult to add them to `friction/js/friction/DragHandler`. (maybe I should rename to `FrictionDragHandler` while I'm at it.

**Comment by terracoda** [comment]
@zepumph, this works pretty well. I seem to hear the warming alerts less often, but regularly hear the breakaways and the cooling alerts. I can do some more testing when Safari cools down ;-)

**Comment by zepumph** [comment]
@terracoda this shouldn't work well at all at the moment. Please hold off further testing until I have implemented the updates for the mouse drag handler.

**Comment by zepumph** [comment]
@terracoda I would now expect the keyboard and mouse interactions to yield the EXACT same results. Let me know if anything seems weird.

**Comment by terracoda** [comment]
@zepumph, I am not sure if this is a VoiceOver issue, but I only get cooling alerts when I use the mouse.

I'll quit Safari and try again. It could be a performance issue.

**Comment by terracoda** [comment]
These seem to work quite nicely with the mouse now.
Thanks again @zepumph, I'll close this issue.
