### ISSUE TITLE
Performance audit when alerts completed

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#108]
From discussion with @terracoda today, once alert algorithms are set in stone, I need to go through and make sure that things are as performant as possible. The main concern in my view is having too many listeners linked to the amplitude Property. This Property changes very frequently, and is probably the main source of any performance issues we encounter.

**Comment by zepumph** [comment]
One idea I just had, since we have so many listeners linking to the `model.amplitudeProperty`, maybe we could create a "less accurate amplitudeProperty" that only updates when amplitude is different enough (like .1) or so. Here is a recording of amplitudeProperty changing, new/old values:

<details>

 1 null
 1.1071627906976744 1
 1.1033984372093024 1.1071627906976744
 1.1998449079578488 1.1033984372093024
 1.1950455283260175 1.1998449079578488
 1.302208319023692 1.1950455283260175
 1.2985621357304256 1.302208319023692
 1.4378736818786813 1.2985621357304256
 1.4335600608330452 1.4378736818786813
 1.5943042468795567 1.4335600608330452
 1.5885647515907904 1.5943042468795567
 1.6528624668887555 1.5885647515907904
 1.6475733069947116 1.6528624668887555
 1.7225873422418048 1.6475733069947116
 1.7170750627466311 1.7225873422418048
 1.7706564580954682 1.7170750627466311
 1.7642820948463245 1.7706564580954682
 1.785714530347778 1.7642820948463245
 1.780000243850665 1.785714530347778
 1.8014328837489209 1.780000243850665
 1.7949477253674246 1.8014328837489209
 1.8056640453165527 1.7949477253674246
 1.800247053180603 1.8056640453165527
 1.8109631687329284 1.800247053180603
 1.8051680865929831 1.8109631687329284
 1.826600726491239 1.8051680865929831
 1.819659643730572 1.826600726491239
 1.8303759636797001 1.819659643730572
 1.8248848357886611 1.8303759636797001
 1.8356011557377891 1.8248848357886611
 1.8293601118082807 1.8356011557377891
 1.8238720314728558 1.8293601118082807
 1.8345881470251812 1.8238720314728558
 1.8279836296958905 1.8345881470251812
 1.8221340820808636 1.8279836296958905
 1.8163032530182048 1.8221340820808636
 1.8097645613073392 1.8163032530182048
 1.8036113617988943 1.8097645613073392
 1.7978398054411378 1.8036113617988943
 1.791727150102638 1.7978398054411378
 1.7867103140823506 1.791727150102638
 1.7802781569516541 1.7867103140823506
 1.7742252112180186 1.7802781569516541
 1.7681928454998774 1.7742252112180186
 1.7625346283942778 1.7681928454998774
 1.7561895037320583 1.7625346283942778
 1.7505696973201157 1.7561895037320583
 1.7446177603492274 1.7505696973201157
 1.7390349835161099 1.7446177603492274
 1.7334700715688582 1.7390349835161099
 1.7275762733255242 1.7334700715688582
 1.7217025139962174 1.7275762733255242
 1.715504384945831 1.7217025139962174
 1.7100147709140043 1.715504384945831
 1.7042007206928969 1.7100147709140043
 1.698406438242541 1.7042007206928969
 1.6929715376401648 1.698406438242541
 1.6872154344121884 1.6929715376401648
 1.6818163450220693 1.6872154344121884
 1.6757618061799897 1.6818163450220693
 1.6700642160389778 1.6757618061799897
 1.6647200105476532 1.6700642160389778
 1.6590599625117912 1.6647200105476532
 1.6537509706317535 1.6590599625117912
 1.6481282173316056 1.6537509706317535
 1.6428542070361445 1.6481282173316056
 1.637925644415036 1.6428542070361445
 1.632356697224025 1.637925644415036
 1.6264802131140186 1.632356697224025
 1.6212754764320538 1.6264802131140186
 1.6160873949074712 1.6212754764320538
 1.6102694802858042 1.6160873949074712
 1.6051166179488896 1.6102694802858042
 1.5999802447714533 1.6051166179488896
 1.5945403119392305 1.5999802447714533
 1.5891188748786371 1.5945403119392305
 1.5837158707040497 1.5891188748786371
 1.5776977503953744 1.5837158707040497
 1.5732801966942673 1.5776977503953744
 1.5682457000648458 1.5732801966942673
 1.5629136646846253 1.5682457000648458
 1.5579123409576345 1.5629136646846253
 1.5519922740619956 1.5579123409576345
 1.547646695694622 1.5519922740619956
 1.5420751675901212 1.547646695694622
 1.5371405270538328 1.5420751675901212
 1.5319142492618498 1.5371405270538328
 1.5267057408143596 1.5319142492618498
 1.5215149412955908 1.5267057408143596
 1.516646093483445 1.5215149412955908
 1.5114894967656012 1.516646093483445
 1.5063504324765982 1.5114894967656012
 1.5012288410061778 1.5063504324765982
 1.4964249087149581 1.5012288410061778
 1.4919356339888132 1.4964249087149581
 1.4865646657064535 1.4919356339888132
 1.4812130329099102 1.4865646657064535
 1.4767693938111806 1.4812130329099102
 1.4708623162359358 1.4767693938111806
 1.466743901750475 1.4708623162359358
 1.4614636237041734 1.466743901750475
 1.45678694010832 1.4614636237041734
 1.4518338645119517 1.45678694010832
 1.4471879961455134 1.4518338645119517
 1.4428464321570769 1.4471879961455134
 1.4376521850013113 1.4428464321570769
 1.4327641675723068 1.4376521850013113
 1.4281793222360755 1.4327641675723068
 1.42360914840492 1.4281793222360755
 1.4187688773003433 1.42360914840492
 1.413945063117522 1.4187688773003433
 1.4091376499029227 1.413945063117522
 1.4043465818932528 1.4091376499029227
 1.3998526728311944 1.4043465818932528
 1.3945332326744357 1.3998526728311944
 1.3900707263298775 1.3945332326744357
 1.3853444858603559 1.3900707263298775
 1.3803572457112585 1.3853444858603559
 1.3767683168724092 1.3803572457112585
 1.3718119509316684 1.3767683168724092
 1.366599065518128 1.3718119509316684
 1.3630459079477808 1.366599065518128
 1.3581389426791688 1.3630459079477808
 1.3529780146969879 1.3581389426791688
 1.3491896762558362 1.3529780146969879
 1.344332593421315 1.3491896762558362
 1.340030729122367 1.344332593421315
 1.335474624643351 1.340030729122367
 1.3309340109195638 1.335474624643351
 1.3232145936562303 1.3309340109195638
 1.3179217352816053 1.3232145936562303
 1.3131772170345914 1.3179217352816053
 1.3089750499400807 1.3131772170345914
 1.3047863297802724 1.3089750499400807
 1.2998281417271074 1.3047863297802724
 1.2961886229302715 1.2998281417271074
 1.2912631061631363 1.2961886229302715
 1.287905822087112 1.2912631061631363
 1.283011779963181 1.287905822087112
 1.278906142267299 1.283011779963181
 1.2743020801551366 1.278906142267299
 1.2704791739146712 1.2743020801551366
 1.2659054488885784 1.2704791739146712
 1.2613481892725795 1.2659054488885784
 1.2570596054290528 1.2613481892725795
 1.2540426623760232 1.2570596054290528
 1.2492773002589943 1.2540426623760232
 1.2455294683582174 1.2492773002589943
 1.2405473504847846 1.2455294683582174
 1.237073817903427 1.2405473504847846
 1.2328677669225554 1.237073817903427
 1.2286760165150188 1.2328677669225554
 1.2244985180588677 1.2286760165150188
 1.2200903233938556 1.2244985180588677
 1.216430052423674 1.2200903233938556
 1.2122941902454336 1.216430052423674
 1.2076874723225008 1.2122941902454336
 1.2045474848944624 1.2076874723225008
 1.1997292949548846 1.2045474848944624
 1.196609998788002 1.1997292949548846
 1.1927808467918803 1.196609998788002
 1.188725391912788 1.1927808467918803
 1.1837327452667543 1.188725391912788
 1.1806550401290608 1.1837327452667543
 1.1761685509765702 1.1806550401290608
 1.1719343441930545 1.1761685509765702
 1.1677153805539595 1.1719343441930545
 1.1651464067167407 1.1677153805539595
 1.161184908933904 1.1651464067167407
 1.1570046432617418 1.161184908933904
 1.1526080256173472 1.1570046432617418
 1.1489196799353718 1.1526080256173472
 1.1454729208955656 1.1489196799353718
 1.1413492183803415 1.1454729208955656
 1.1379251707252005 1.1413492183803415
 1.1340562251447348 1.1379251707252005
 1.1302004339792429 1.1340562251447348
 1.1261317124169175 1.1302004339792429
 1.12297854362215 1.1261317124169175
 1.1189358208651101 1.12297854362215
 1.1153552262383417 1.1189358208651101
 1.1113399474238836 1.1153552262383417
 1.1066723196447033 1.1113399474238836
 1.104016306077556 1.1066723196447033
 1.1007042571593233 1.104016306077556
 1.096301440130686 1.1007042571593233
 1.0934510563863462 1.096301440130686
 1.0895146325833553 1.0934510563863462
 1.0855923799060552 1.0895146325833553
 1.0827698397182994 1.0855923799060552
 1.0784387603594263 1.0827698397182994
 1.0747720685742044 1.0784387603594263
 1.0715477523684818 1.0747720685742044
 1.0679044900104289 1.0715477523684818
 1.0642736147443934 1.0679044900104289
 1.0604422297313136 1.0642736147443934
 1.0568367261502272 1.0604422297313136
 1.0540889506622366 1.0568367261502272
 1.05008341264972 1.0540889506622366
 1.0465131290467111 1.05008341264972
 1.0425363791563336 1.0465131290467111
 1.039825784570527 1.0425363791563336
 1.035874446589159 1.039825784570527
 1.0329739981387094 1.035874446589159
 1.0296684813446655 1.0329739981387094
 1.0259616748118245 1.0296684813446655
 1.0218578281125772 1.0259616748118245
 1.0192009977594845 1.0218578281125772
 1.0153280339679984 1.0192009977594845
 1.0126881810796815 1.0153280339679984
 1.0088399659915788 1.0126881810796815
 1.0060152140868024 1.0088399659915788
 1.0015887471448206 1.0060152140868024
 1 1.0015887471448206
</details>

**Comment by zepumph** [comment]
In the above commit, we don't have to calculate the new temp/jiggle strings every time amplitude changes, instead only when it changes and temp isn't decreasing/`amplitudeSettledButNotMin`

**Comment by zepumph** [comment]
Things are a bit more settled algorithmically. I'm marking off hold.

**Comment by terracoda** [comment]
Good idea :-) I have gotten this Safari browser alert a couple of times. I am not sure if this alert is new to this version of Safari (11.1.2), but I never used to get this alert when testing BASE. Voice Over would just say "Safari Busy" when things got to be too much.

**Comment by zepumph** [comment]
I looked through all the code, and nothing incredibly obnoxious stood out to me. If we need to take a closer look later we can. I simplified quite a bit of code in the last 24 hours, so I wonder if things are simpler/more performant now? 

My main worry was about linking to the amplitude property, and those places look pretty good, and very optimizable. Closing
