### ISSUE TITLE
Gently communicate existance of "air space" between books

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#111]
In meeting last Tuesday we discussed the need to communicate to users (especially blind users) when there is air space between the Chemistry Book and the Physics Book and there is then a need to "move down to rub harder". 

I have sketched out some phrase changes in the scene summary that include the words "lightly" and "hard" or "harder" that may help communicate the air space. (edited for clarity and typos)

I outline two approaches in design document:
1. Just change sentence three, or
2. Combine some wording changes to both sentence 1 and sentence 3 of the scene summary.

Changes are sketched out in the design doc in the section titled:
[Parameters for dynamic screen summary information](https://docs.google.com/document/d/1v7GM_dNZs86jcRn2X03D2t7HFDb4dQ1h4ayDGXTu63U/edit#heading=h.e8gf0dy8lzle)

**Comment by terracoda** [comment]
@zepumph and @emily-phet, I will put this idea on Design/Dev Meeting Agenda, but feel free to comment sooner if you like.

**Comment by emily-phet** [comment]
@terracoda Please put this on the agenda (in the Friction design doc) for the Friction meeting Tuesday at 11:30-noon MT.

**Comment by terracoda** [comment]
@emily-phet, oh, thanks! I forgot that this goes in the design doc now. I'll move it to there from the Des/Dev updates Agenda.

**Comment by terracoda** [comment]
When we fix the scene summary, the word "thermometer" should also be included. This is just a reminder to self as I closed issue #104 in favour of this issue.

**Comment by terracoda** [comment]
At meeting yesterday, we decided to take the most simple and elegant solution of changing both the first and third sentences (option 2 in https://github.com/phetsims/friction/issues/111#issue-358616293)

**Comment by terracoda** [comment]
@zepumph, I'll clean up the design doc to make it clear what to implement ;-)

**Comment by zepumph** [comment]
Basically this issue is now just to make sure that the screen summary is updated to what is currently in the design document (don't forget about the thermometer stuff in https://github.com/phetsims/friction/issues/104). I'll get on it!

**Comment by terracoda** [comment]
@zepumph, you probably already noticed that there are no longer 2 options in the design doc. I updated it and removed the option we are not using.

**Comment by zepumph** [comment]
I think that I have implemented everything in the screen summary section of the design doc but one thing (I also commented in the doc).

I see that in a settled state, this is the second sentence:
`In  zoomed-in view of where books meet, atoms {{jiggle a tiny bit}}, and {{surface temperature thermometer is cool}}.`
But when in transition, the surface temp/atoms clauses are swapped. Instead can we have it be in the same order the whole time i.e. in a settled state:

In  zoomed-in view of where books meet, {{surface temperature thermometer is cool}}, and atoms {{jiggle a tiny bit}}.

@terracoda what do you think? My suggestion above is how it is currently implemented (part of the reason for the request), so if you think that is alright, please review the rest of the changes too.

**Comment by terracoda** [comment]
This sounds great @zepumph! I think we can close this issue.
