### ISSUE TITLE
Is the downloaded Built version the same version? 

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#114]
@zepumph, I was having some performance issues so I thought I would try running the downloaded sim instead of the direct build, so I could turn off the VPN.

The downloaded version seems to behave differently (fewer warming alerts), almost like previous version?

Do you have to update the built version, too, or do you think I might just be having continued performance issues?

**Comment by zepumph** [comment]
To run a downloaded version, follow the following steps, and let me know if you have issues (sorry if this is a bit redundant, I want to be thorough)

* Got to phettest.colorado.edu, pull all, and go to the line for friction
* Click the "Build" button
![image](https://user-images.githubusercontent.com/6856943/45574714-600fa300-b81d-11e8-9296-80edfe53f21f.png)
* Once build is complete, right click (or mac equivalent) on the "Built Version" link, and "save link" or something like that, on windows chrome it says "Save Link as . . ."
* That should be a link that is identical to the requirejs mode. Please report if it is not.

**Comment by zepumph** [comment]
I just tested this, on windows NVDA and things sounded fine. Can you test in the a11y view and see if you can see the alerts coming through, but perhaps not being alerted by VO for some reason?

**Comment by terracoda** [comment]
Oh, I didn't follow all those steps so that is why I was running an old version! Thanks @zepumph.

**Comment by zepumph** [comment]
@terracoda is this ready to close?

**Comment by terracoda** [comment]
Thanks @zepumph, yes. Closing.
