### ISSUE TITLE
Often not hearing settled focus state when focus is on book or zoomed-n book

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#115]
@zepumph, I was hearing this alert fine on Monday and Tuesday, but not today. I am not sure if this is a performance issue or if something changed.

Using Safari 11.1.2.

On focus I should hear:
- "Chemistry book, move in four direction. Atoms jiggle a tiny bit, temperature cool."

But often only hear:
- "Chemistry book, move in four direction."

Has something changed about the focus alert since yesterday?

**Comment by zepumph** [comment]
I just tested this, on windows NVDA and things sounded fine. Can you test in the a11y view and see if you can see the alerts coming through, but perhaps not being alerted by VO for some reason?

**Comment by zepumph** [comment]
>"Chemistry book, move in four direction. Atoms jiggle a tiny bit, temperature cool."

Also a note on implementation, these are two different systems, the "Atoms jiggle . . " alert is just that, an alert through aria-live (although it happens onFocus). The previous stuff comes from the screen reader focusing on the elements (at least that's my understanding).

**Comment by terracoda** [comment]
Your understanding about AT read out and alert via aria-live are correct.

**Comment by zepumph** [comment]
@terracoda can you please comment on https://github.com/phetsims/friction/issues/115#issuecomment-421483569

**Comment by terracoda** [comment]
@zepumph, this is a Voice Over issue. In the A11y View, I see the alerts every time, and when I restarted Safari and Voice Over and I heard the alerts again.

I expect this weird behaviour from Voice Over. When I posted this issue it seemed more prominent than usual.

I'll close this issue, as this is a known Voice Over bug.
