### ISSUE TITLE
If easy, add in a cooling alert, "Jiggling less, now cooler."

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#118]
@zepumph, I'm just moving a closed comment from the design document to an issue so it can be tracked better. This issue is somewhat related to #112.

When we talked last Friday about the cooling alerts, I think I mentioned that it too many repeated alerts sometimes is not is not useful for blind users. I think we were specifically discussing, "Jiggling less, cooler" and how many times it should repeat before "Jiggling even less, even cooler."

I realized today when reviewing the design doc that we could slip in a wording change, "now cooler", so even after the briefer first cooling alert fires, there is still a wording change between alerts.

For example, first cooling sequence sounds like this:
- Jiggling less, temperature cooler.
- Jiggling less, now cooler. 
- Jiggling less, even cooler.

Subsequent cooling sequences sounds like this:
- Jiggling less, cooler.
- Jiggling less, now cooler. 
- Jiggling less, even cooler.

This change is not a high priority as things are sounding pretty good as is. My though was if it is easy to implement, it would be great to make the change, and it might even create a bit more symmetry with the warming alerts.

**Comment by zepumph** [comment]
Sounds good. I will implement it as desired above. I will also remove the `oneJigglingLessNowCoolerAlerts` query parameter because it won't make sense after these changes.

**Comment by zepumph** [comment]
I made only minimal changes to try to get the idea of what you were going for above. Much of the above examples were only slightly different from what is currently in the code. Here is what the current sequences look like:
First Sequnce:
* Atoms jiggling less, temperature cooler
* Jiggling less, now cooler
* Jiggling even less, even cooler
* Atoms jiggle a tiny bit, temperature cool

Subsequent:
* Jiggling less, cooler
* Jiggling less, now cooler
* Jiggling even less, even cooler
* Atoms jiggle a tiny bit, temperature cool

How does that sound @terracoda?

**Comment by terracoda** [comment]
@zepumph, I verified this is Voice Over. Sounds great, thanks!
