### ISSUE TITLE
Can't reset the sim with the reset button

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#120]
@zepumph, I was just trying to verify #112, and after i start interacting, I can't seem to reset the sim with the reset button. I have to refresh the browser.

Might this be related to #112? 

I am still trying to figure out how to reproduce. 

And, FYI, in the a11y view, the alerts seems to stop, which my also be related, but I will create a separate issue for that.

**Comment by terracoda** [comment]
@zepumph there seems to be more going on... I used the mouse and did a reset, and then I couldn't use the mouse, only the keyboard to interact with the book. I'll create an issue for that, too.

To reproduce this  issue - Can't reset sim with reset button,
1. Using the keyboard create friction and loose some atoms
2. Tab to Reset button, and try Enter or Space key

**Comment by zepumph** [comment]
Please see https://github.com/phetsims/friction/issues/121

**Comment by terracoda** [comment]
I can reset again :-) Thanks!
