### ISSUE TITLE
Can't use sim with mouse after a reset

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#121]
This may be related to issue #120.

I use the sim with the mouse, loose some particles, reset the sim and then I can't use the sim with a mouse, only the keyboard, and while I can't move the book, I can't reset the sim.

**Comment by zepumph** [comment]
I think the above fixed the issue, please review.

**Comment by terracoda** [comment]
I can use the mouse after a reset! Great work @zepumph!
