### ISSUE TITLE
Ready links for interviews tomorrow

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#123]
We will need a link to the sonified version, as well as just the described version.

**Comment by zepumph** [comment]
After talking with @terracoda, we think that it makes sense to make links for where the sim was this morning, which had a few more left/right alerts, but in general was working pretty well, as well as new links after I worked on #116 more. So this issue will have 4 links in them.

**Comment by zepumph** [comment]
Here are the links with MORE left/right links, everytime you move, even when books are touching:

described:
https://phet-dev.colorado.edu/html/friction/1.5.0-dev.15/phet/friction_all_phet.html?accessibility

sonified:
https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.74/phet-io-wrapper-sonification/friction/html/friction-sonification.html?sonificationFile=sonificationDefault&accessibility

**Comment by zepumph** [comment]
Here are the links with less left/right links, when the books are touching, you should only get one "set" of left/right before you don't get those alerts anymore:

described:
https://phet-dev.colorado.edu/html/friction/1.5.0-dev.16/phet/friction_all_phet.html?accessibility

sonified:
https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.75/phet-io-wrapper-sonification/friction/html/friction-sonification.html?sonificationFile=sonificationDefault&accessibility

**Comment by zepumph** [comment]
@terracoda over to you. Let me know if you need anything else.

**Comment by terracoda** [comment]
That should do it @zepumph, thanks for all your hard work!
