### ISSUE TITLE
Put intial interaction hint in its own paragraph.

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#129]
In 2 recent interviews, both participant jumped over the last part of the summary paragraph that read, "move down to rub harder."

To make sure users do not miss this hint, @zepumph suggested we move it in to its own paragraph, which makes total sense and which is how I have done it in sims that have more complex opening summaries.

I'll update design document, and this issue asap.

**Comment by terracoda** [comment]
@zepumph, I made the new paragraph more obvious in the design document, and this is just a reminder issue so this little detail doesn't get forgotten.

**Comment by zepumph** [comment]
Implemented above. @terracoda please review.

**Comment by terracoda** [comment]
This sounds great @zepumph. It is very difficult to skip over the hint now. Closing.
