### ISSUE TITLE
Need latest sound and text version for meeting with consultants

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#145]
Heads up issue! Please port latest description to latest sonification wrapper.
I have two meetings one for Thursday afternoon MT and one for Friday morning MT (exact times to be added).

Hopefully there is enough time to allow to get the latest sound version.

@zepumph, the Grab button alerts do not need to be perfect. We want to verify the cooling sound. I can always discuss the alerts with the consultants.

I think I will need a link to the sonification wrapper when everything is ported.

Tagging @jbphet, too.

**Comment by jbphet** [comment]
@zepumph - I assume that you've got this, but please let me know if I can assist in any way.

**Comment by terracoda** [comment]
@zepumph, I this link will meet my needs for Thursday and Friday for Friction:
[](https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.83/phet-io-wrapper-sonification/friction/html/friction-sonification.html?sonificationFile=sonificationDefault&accessibility)

**Comment by zepumph** [comment]
Currently there is a lot of churn in Friction. I am updating the visual cues for the grab interface and cueing arrows. I do not think there will be anything better for you than the above link before tomorrow.

**Comment by zepumph** [comment]
I'm going to close this issue. Please reopen or let me know if you need anything more @terracoda.

**Comment by terracoda** [comment]
Thanks @zepumph! I will use the link above.
