### ISSUE TITLE
Fate of 'cooling' sound

### ISSUE THREAD

**Issue by emily-phet** [phetsims/friction#146]
Ok folks - I'd like to make a decision if we're going to keep the cooling off sound, and if so, if it should go in as an 'enhanced' sound. 

The rest of the sound design is complete, as well as the description (essentially) so new interviews would likely only be arranged to get feedback on this sound. I'd prefer not to put time into further interviews for this sim, particularly for a sound that is more of a 'background' sound. So I'd like to see if we can come to consensus with the information, and general feeling, that we have currently.

My take - it seems like there's not definitive evidence from interviews that it's useful, but I also haven't gotten the impression that's it's harming anything. I'd be inclined to include it as an enhanced sound.

@briannatomlinson - (I spoke with her today) Had a similar feeling. Nothing she's seen would indicate a problem coming from the sound being present, and she thought it could be serving as a productive (subtle) dual cueing. She said she would feel fine about having the sound in the sim, particularly in the enhanced setting.

@terracoda and Ashton (I need to get Ashton added to this repo) - please weigh in if you have strong feelings on this or not.

**Comment by Ashton-Morris** [comment]
I feel like it reinforces the concept and provides an additional layer of information in terms of accessibility. I think we should keep it in and not adjust the volume any louder as it is one of those sounds that can get irritating if too present.

**Comment by terracoda** [comment]
@emily-phet, I agree, I think the sounds are working well and are creating a pleasant experience for users.

The cooling sound is not causing any problems (not getting in the way), and I think it can add some due cuing about cooling as others have mentioned. I would be most comfortable if it was implemented as an enhanced sound, so that due cuing could be made more explicit when needed.

**Comment by terracoda** [comment]
I think we all agree, @emily-phet are we ready to assign this for implementation?

**Comment by emily-phet** [comment]
@jbphet already started an issue to work on this.
