### ISSUE TITLE
Help text for books doesn't seem right

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#147]
From work on https://github.com/phetsims/friction/issues/126.

@terracoda could you please comment on the "help text" for the two draggable book views. This is what I currently have in between the two buttons in the PDOM:

`Look for grab buttons. Once grabbed, use letter keys W, A, S, or D to move book or zoomed-in book up, left, down, or right.`

but then once grabbed, there is also this next to the application div ('sorry that it is currently IN the button right now, please ignore that for this issue).

`Use arrow keys, or letter keys W, A, S, or D to move book or zoomed-in book up, left, down, or right.`

Does that sound right to you?

**Comment by zepumph** [comment]
I'm using the a11y view to see this, rather than a screen ready. Maybe you can figure out out to hear both on a screen ready, but I couldn't.

**Comment by terracoda** [comment]
@zepumph, I explained this in a different issue, can you look here in this comment?
https://github.com/phetsims/friction/issues/126#issuecomment-435569891

**Comment by zepumph** [comment]
Oh my goodness there it is! I could not remember what issue that comment was, so I just made a new issue. Thanks!
