### ISSUE TITLE
Add Book pick up and drop sound to keyboard interaction (alternative input)

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#157]
Related to https://github.com/phetsims/friction/issues/148.

This is likely already on John and Ashton's radar. At Dec 11th meting we noted that we need the book pick and drop sound to work for alternative input as well (keyboard).

The keys to grab and release the book or zoomed-in book are:
- grab: Space or Enter keys
- release: Space, Enter, or Escape keys

Assigning to @Ashton-Morris and @jbphet, please re-assign as needed to the correct person, and re-assign to me if you like for verification.

**Comment by terracoda** [comment]
Just referencing my comment from the visual grab interaction issue: https://github.com/phetsims/friction/issues/142#event-2021350264

**Comment by jbphet** [comment]
I've implemented, and this feature can be experienced in https://phet-dev.colorado.edu/html/friction/1.5.0-dev.24/phet/friction_en_phet.html.  @terracoda - please try it out and, if it works, close this issue.

**Comment by terracoda** [comment]
@jbphet sounds great, thanks, and closing issue.
