### ISSUE TITLE
Lines from chemistry book can be seen in physics book

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/friction#162]
**Test Device**

MacBook Air

**Operating System**

macOS 10.14

**Browser**

Chrome 71.0.3578.98

**Problem Description**

For https://github.com/phetsims/QA/issues/244. When moving the chemistry book, a line meant to look like a page will appear and disappear near the bottom of the book. (I think this is a line from the physics book.)

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/50363111-8f723200-0527-11e9-96dd-ec8386f8179d.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.5.0-rc.1/phet/friction_en_phet.html
Version: 1.5.0-rc.1 2018-12-20 22:49:42 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"69088d35","branch":"HEAD"},"axon":{"sha":"dd291081","branch":"HEAD"},"brand":{"sha":"b2f1706d","branch":"HEAD"},"chipper":{"sha":"e95d808c","branch":"HEAD"},"dot":{"sha":"8d95f26a","branch":"HEAD"},"friction":{"sha":"72616640","branch":"HEAD"},"joist":{"sha":"64ed222e","branch":"HEAD"},"kite":{"sha":"6c78a24f","branch":"HEAD"},"phet-core":{"sha":"9d80d6a8","branch":"HEAD"},"phet-io":{"sha":"4558068d","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"a066df33","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b19f6689","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"6f3a9e13","branch":"HEAD"},"phet-io-wrappers":{"sha":"9b59dfbc","branch":"HEAD"},"phetcommon":{"sha":"f8c5396f","branch":"HEAD"},"query-string-machine":{"sha":"96ab0c2b","branch":"HEAD"},"scenery":{"sha":"1132d106","branch":"HEAD"},"scenery-phet":{"sha":"4cdcf780","branch":"HEAD"},"sherpa":{"sha":"a1f5e867","branch":"HEAD"},"sun":{"sha":"19bb3f43","branch":"HEAD"},"tambo":{"sha":"e6ea10d9","branch":"HEAD"},"tandem":{"sha":"eb385888","branch":"HEAD"}}
</summary>

**Comment by zepumph** [comment]
Cherry picked above.

**Comment by KatieWoe** [comment]
Looks good 1.5.0-rc.2
