### ISSUE TITLE
Can't drag book up after keyboardnav

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#164]
**Test device:**
Dell Laptop and Chromebook
**Operating System:**
Win 10 and ChromeOS
**Browser:**
Chrome
**Problem description:**
May be related to https://github.com/phetsims/friction/issues/39.  For https://github.com/phetsims/QA/issues/244.
When starting to drag a book after it has been moved with keyboard nav, the mouse may be unable to drag up.  It can still drag side to side and down.  Releasing the mouse and redragging fixes the problem.  It only occurs if one of the focuses was last "active" ie. with a dotted border.  It does not matter if the focus was actually on the book last.
**Steps to reproduce:**
1. Use keyboard nav to move one of the books back and forth
2. Stop moving the book at a point where it is neither as far up, or as far down as it can go
3. Click to drag either book.  Do Not Let Go
4. Note that the book can be dragged in any direction but up
5. Let go
6. Re-click to drag and note that the behavior is fixed.

**Screenshots:**
https://drive.google.com/file/d/1j6MknNmgdG3TlfVwn-tZWKx2n9UpeamO/view?usp=sharing

<details>
<summary><b>Troubleshooting information</b></summary>

Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.5.0-rc.1/phet/friction_en_phet.html
Version: 1.5.0-rc.1 2018-12-20 22:49:42 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"69088d35","branch":"HEAD"},"axon":{"sha":"dd291081","branch":"HEAD"},"brand":{"sha":"b2f1706d","branch":"HEAD"},"chipper":{"sha":"e95d808c","branch":"HEAD"},"dot":{"sha":"8d95f26a","branch":"HEAD"},"friction":{"sha":"72616640","branch":"HEAD"},"joist":{"sha":"64ed222e","branch":"HEAD"},"kite":{"sha":"6c78a24f","branch":"HEAD"},"phet-core":{"sha":"9d80d6a8","branch":"HEAD"},"phet-io":{"sha":"4558068d","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"a066df33","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b19f6689","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"6f3a9e13","branch":"HEAD"},"phet-io-wrappers":{"sha":"9b59dfbc","branch":"HEAD"},"phetcommon":{"sha":"f8c5396f","branch":"HEAD"},"query-string-machine":{"sha":"96ab0c2b","branch":"HEAD"},"scenery":{"sha":"1132d106","branch":"HEAD"},"scenery-phet":{"sha":"4cdcf780","branch":"HEAD"},"sherpa":{"sha":"a1f5e867","branch":"HEAD"},"sun":{"sha":"19bb3f43","branch":"HEAD"},"tambo":{"sha":"e6ea10d9","branch":"HEAD"},"tandem":{"sha":"eb385888","branch":"HEAD"}}

</details>

**Comment by zepumph** [comment]
The issues is that pressing the book down with the keyboard drag handler continues to move the book position (in the model) down, but the view is stopped by the bottom book. You can confirm this by moving the book down with keyboard nav to touch the bottom book, then moving it down only once or twice more. Then with the mouse move the book way up, you should be able to eventually move it off of the bottom book.

**Comment by KatieWoe** [comment]
1.5.0-rc.2 seems fixed
