### ISSUE TITLE
Moving book with WASD in fullscreen causes Mac "funk" noise

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/friction#167]
**Test Device**

Dirac

**Operating System**

macOS 10.10.5
macOS 10.11.6

**Browser**

Safari

**Problem Description**

For https://github.com/phetsims/QA/issues/244. In fullscreen, if the book is moved with WASD, the Mac "funk" noise is heard.

Funk Noise: https://www.youtube.com/watch?v=8rz44o_gGpE

**Comment by jessegreenberg** [comment]
@lmulhall-phet @KatieWoe  do you know if this has ever happened in BASE? For instance, does it happen with https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html?phetioValidateTandems in full screen mode?

**Comment by KatieWoe** [comment]
Seems to yes

**Comment by jessegreenberg** [comment]
OK, that is helpful, thanks.

**Comment by KatieWoe** [comment]
Seems fixed on master @zepumph 
I checked on a 10.13.6 device, but the issue was present in the rc on this platform as well.

**Comment by zepumph** [comment]
Thanks for checking! I have not yet cherry-picked this into master, but will do so to the branch soon.

**Comment by zepumph** [comment]
f65f46f07c7533cb5eda69479c236e4f56b9a5d3

**Comment by KatieWoe** [comment]
1.5.0-rc.2 looks good

**Comment by JRomero0613** [comment]
I have been testing on 1.5.0-rc.2 on Safari on MacOS 10.12.6 and have seen this issue occur. This occurs when the book has been navigated to using tab, but has not been picked up using space. The outline around the book should be a solid pink line to get the "funk" noise to occur. If the book has been picked up the noise will not occur.

**Comment by KatieWoe** [comment]
https://github.com/phetsims/QA/issues/276

**Comment by zepumph** [comment]
>Since you can't move the book until it has been picked up, this may be intended. @zepumph?

I agree. Arrow keys should not do anything in the sim when the book has not been grabbed. Since the "solid red lined" book is basically the same type of button as highlighting the reset all button, I would think this behavior is expected. I'm ready to close this if that seems alright to @JRomero0613.

**Comment by zepumph** [comment]
Sounds fine to @jessegreenberg and I, @JRomero0613 please close once you have reviewed this.

**Comment by zepumph** [comment]
I'm going to close this. @JRomero0613 let me know if you have any other questions.
