### ISSUE TITLE
Should you be able to move the magnified book by dragging the white above it?

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#169]
This is a design question for @ariel-phet. Currently you can click the white above the magnified lens to drag the book (as noted by my highlighing art):
![image](https://user-images.githubusercontent.com/6856943/50663631-c77d6a00-0f56-11e9-8a15-e0c3f066303f.png)

Do we want this? It seemed like a bug to me, but there are some cases where if you don't have it you have to click pretty accurately to get the book back. I also wasn't involved in the design of this sim at all, so I don't know if this was a conscious decision. Should be keep this white draggable?

**Comment by zepumph** [comment]
In the currently published version you can drag the white background above the book, https://phet.colorado.edu/sims/html/friction/latest/friction_en.html

**Comment by ariel-phet** [comment]
That was not a conscious decision and seems like bad UX to me.

**Comment by zepumph** [comment]
Implemented above both in master and branch 1.5
