### ISSUE TITLE
Update credits please

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#176]
From https://github.com/phetsims/a11y-research/issues/134#issuecomment-467948060

Please add Taliesin Smith to the Team list in the About... credits.

**Comment by zepumph** [comment]
Maintenance release published! Sorry for the delay,
https://phet.colorado.edu/sims/html/friction/latest/friction_en.html

**Comment by terracoda** [comment]
Thanks @zepumph, and definitely no apology necessary :-) I just posted the issue!

**Comment by terracoda** [comment]
Ooops, re-opening this issue as we missed **Brianna Tomlinson** in the credits, too.
On next deploy, please add **Brianna Tomlinson** to team list, and also re-arrange team list into alphabetical order by last name, so the last three names should be:
- Taliesin Smith, Brianna Tomlinson, Carl Wieman

**Screen shot from June 18, 2019**
<img width="620" alt="credits-friction" src="https://user-images.githubusercontent.com/1902116/59674378-79d28200-91c3-11e9-98c1-646b2c67b4d2.png">

@emily-phet, do you want your middle initial? I noticed in some credits, your initial is not present. Assigning to @emily-phet for clarification on her name in case it needs to be updated, too.

**Comment by zepumph** [comment]
@emily-phet I see 12 usages of `Emily Moore` and 14 of `Emily B. Moore` in the code base. Whatever you decide, would you like me to propagate to all places?

**Comment by emily-phet** [comment]
thanks! I prefer "Emily B. Moore" since "Emily Moore" is such a common name.

**Comment by emily-phet** [comment]
And yes, if it's straightforward please propagate.

**Comment by zepumph** [comment]
@emily-phet your name was propagated with the "B" in https://github.com/phetsims/resistance-in-a-wire/issues/208. Credits have been updated. Closing.
