### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#177]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* No needed changes noticed
* books don't have pointer areas

Screenshots:
![Image from iOS](https://user-images.githubusercontent.com/41024075/55912424-df8d0700-5b9f-11e9-877a-98d27da8d37a.png)

**Comment by arouinfar** [comment]
I think the lack of visible pointer areas means that click/touch areas are the exact boundaries of the book. Is that correct @zepumph? If not, then it would be nice to see the boundaries in `showPointerAreas`. Otherwise, I think this is safe to close.

**Comment by zepumph** [comment]
Yes that is correct! It is confusing, and devs often use the wrong terminology, but basically pointer areas are a supplementary way to add to the region that is clickable/touchable to interact with a Node. The whole area that you can interact with  a given Node for is called a "hit area"

>it would be nice to see the boundaries in `showPointerAreas`

Yes agreed that would be nice. Right now we don't have support for a `?showHitAreas` query parameter, but I think the issue to track that will be https://github.com/phetsims/sun/issues/426
