### ISSUE TITLE
Organize a11y strings into nested object

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#180]
From https://github.com/phetsims/rosetta/issues/193, though we are still on a branch, we can now move a11y strings around into nested objects to make things more clear.

**Comment by zepumph** [comment]
This went very well. For the most part no comments were really needed, any when I felt like they were, it was really because the organization was designed differently than it should be given the current nesting object support, and so the fix was really refactoring instead of adding extra comments. Closing

**Comment by zepumph** [comment]
This has been implemented, but I should not close it. Instead it should be reviewed as part of phetsims/rosetta#193

**Comment by zepumph** [comment]
@samreid, we looked at this in large part today, but this issue is mainly to review the implementation in the sim. Does everything look alright there?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
