### ISSUE TITLE
Placement of the visual cue for keyboard navigation is incorrect

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#181]
Just noticed while spot checking for another issue. It is located here:

![image](https://user-images.githubusercontent.com/6396244/65364158-f2d7e000-dbdd-11e9-8cc9-020a413eea41.png)

Assigning to @zepumph since he is responsible dev but let me know if I can help. May be related to KeyboardDragListener.

**Comment by zepumph** [comment]
Thanks @jessegreenberg. Hows that?

**Comment by jessegreenberg** [comment]
Beautiful, thnk you!
