### ISSUE TITLE
iPad Reset Freeze

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#185]
For ES6 Testing. 
Seen on iPad 13 and 12, but not on Win 10.
When you hit the reset all button the sim freezes. Looking at the console you see an error that reads:
```
Error: Assertion failed: describedby association already registed
```

**Comment by zepumph** [comment]
Thanks!

**Comment by zepumph** [comment]
I can use this in correlation with https://github.com/phetsims/chipper/issues/845 to help debug the case

Index: friction/js/friction/view/FrictionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- friction/js/friction/view/FrictionScreenView.js	(revision 3bfbb998f8890d32a92d5cdb824848abff8618c3)
+++ friction/js/friction/view/FrictionScreenView.js	(date 1582919813685)
@@ -12,6 +12,7 @@
 import ScreenView from '../../../../joist/js/ScreenView.js';
 import inherit from '../../../../phet-core/js/inherit.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
+import DebugLoggerNode from '../../../../scenery-phet/js/DebugLoggerNode.js';
 import ThermometerNode from '../../../../scenery-phet/js/ThermometerNode.js';
 import SoundClip from '../../../../tambo/js/sound-generators/SoundClip.js';
 import SoundLevelEnum from '../../../../tambo/js/SoundLevelEnum.js';
@@ -69,6 +70,9 @@
     screenSummaryContent: frictionScreenSummaryNode
   } );
 
+  phet.debugLoggerNode = new DebugLoggerNode();
+  this.addChild( phet.debugLoggerNode );
+
   // @private
   this.model = model;
 
Index: scenery/js/accessibility/Accessibility.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/Accessibility.js	(revision 07da7de8a96ffda07bc8c45453c94f0efe9d97e8)
+++ scenery/js/accessibility/Accessibility.js	(date 1582919884495)
@@ -1737,6 +1737,8 @@
         assert && AccessibilityUtils.validateAssociationObject( associationObject );
         assert && assert( !_.includes( this._ariaDescribedbyAssociations, associationObject ), 'describedby association already registed' );
 
+
+        !_.includes( this._ariaDescribedbyAssociations, associationObject ) && phet.debugLoggerNode.log( new Error().stack );
         this._ariaDescribedbyAssociations.push( associationObject ); // Keep track of this association.
 
         // Flag that this node is is being described by the other node, so that if the other node changes it can tell

**Comment by KatieWoe** [comment]
Looks ok from what I can see.
