### ISSUE TITLE
Launched sim still has missing particles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#186]
For ES6 Testing
When launching the sim from studio, any particles that were removed will reappear. This can also lead to the books overlapping.

**Comment by KatieWoe** [comment]
Appearance in state wrapper:
![happensinstate](https://user-images.githubusercontent.com/41024075/76253374-37991700-6210-11ea-8ade-62a296af97db.gif)

**Comment by zepumph** [comment]
Unassigning until we work on Friction PhET-iO state.

**Comment by zepumph** [comment]
Fixed in https://github.com/phetsims/friction/commit/90206562b1e5b917733fbcdf4d3d48c684caae32 and https://github.com/phetsims/friction/commit/8efc258dd9b829c63bef45366e631a4eccad0100

We are now tracking state in friction atoms.
