### ISSUE TITLE
move a11y strings into main strings json

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#187]
From phetsims/chipper#795

**Comment by zepumph** [comment]
On a branch I have already done this, perhaps I can use some of that logic on master. https://github.com/phetsims/friction/issues/178

**Comment by zepumph** [comment]
@jessegreenberg please spot check.

**Comment by jessegreenberg** [comment]
I did a spot check by inspecting the nested strings in friction-strings_en.json and verifying behavior of the a11y view. Nesting looks great and seems logical, behavior is good. Closing.
