### ISSUE TITLE
(Self-Voicing) Need to voice button names on focus

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#190]
The self-voicing of Friction is coming along great. I just tested the latest in Firefox on MacOS 10.13.6 (kind of of oldish, I know) and I do not hear the grab button names on focus or the Reset All button name on focus.

On focus of a button, I need to hear the button's name (no role, just the name). The name identifues an interactive thing. Because buttons are buttons, hopefully the learner will press Space or Enter keys since that is kind of the most intuitive thing try first.

The button names I need for Friction are:
- Grab Chemistry Book
- Grab Zoomed-in Chemistry Book
- Reset All

The sim voices responses when buttons are activated, so that's good!

I'll post less critical issues about the responses in separate issues.

**Comment by terracoda** [comment]
@jessegreenberg, I can work around this for today's interviews, but need it for next week's interviews.

**Comment by terracoda** [comment]
Please add priority level if that's helpful for you :-)

**Comment by zepumph** [comment]
This is now done with the nameResponse option to Voicing.js
