### ISSUE TITLE
(Voicing) Overview wording after a "breakaway" seems to have some kind of mistake in it. It says the word "dot"

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/friction#196]
There may be a misplaced period in the overview. During some interactions, the overview button reads out the word "dot".

**Comment by zepumph** [comment]
This issue has been outdated. The overview button has been reimplemented since voicing was added to master, and it now is the hard coded string from the design doc:

>{{Friction}} is an interactive sim. It changes as you play with it. Warm up your hands and get ready for Friction! There’s a stack of big textbooks ready to go! There is a zoomed-in view so you can see how creating friction affects the atoms of the textbooks.

Closing
