### ISSUE TITLE
"Continue rubbing chemistry book to generate even more friction." hint not in screen summary

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#199]
This string was asked for as a possible hint in the voicing read-me buttons. I didn't see it working in the screen summary, and so it wasn't clear if this was a bug in how the interactive description was implemented, or a purposeful deviation for voicing.

Here is where the design doc for this lives: https://docs.google.com/document/d/1E-ecRqgwMjBHboPw0IXE-1-zB-ZO9_Owskj-QeXJ8S4/edit#heading=h.bgx05dyt2zl7

@Matthew-Moore240 should the interactive description also say this in the screen summary?

**Comment by Matthew-Moore240** [comment]
No, that hint should just be in the hint please area/button.

**Comment by zepumph** [comment]
The hint help button should be perfect now. Please let me know if there is anything else for it.

**Comment by Matthew-Moore240** [comment]
Sounds really good! This seems to be fixed. Closing
