### ISSUE TITLE
Different focusHighlight needed for mouse highlights

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#200]
When I mix in voicing (and thus mouseHighlighting) into the bookNode, on hover I get a highlight that includes the grab cue. This is build into GrabDragInteraction, and would most likely be challenging to change. Instead can we just pass in another focusHighlight to be activated for mouse?

**Comment by jessegreenberg** [comment]
Yes I think that will be necessary. This is not something that is supported yet but I think we need a setter for various kinds of focus highlights.

**Comment by zepumph** [comment]
@jessegreenberg and discussed this an we will first work on phetsims/scenery#1230 to get this working.

**Comment by zepumph** [comment]
https://github.com/phetsims/friction/commit/7fcf8feb33d7e46dd98f908ed8a3903666a87187 looks pretty good, along with review comments in https://github.com/phetsims/scenery-phet/issues/698. I am not seeing this bug anymore in Friction. Do you think there is anything more to do here?

**Comment by jessegreenberg** [comment]
OK, thanks for reviewing https://github.com/phetsims/scenery-phet/issues/698, lets close.
