### ISSUE TITLE
Temperature and jiggling responses while decreasing fire too often.

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/friction#210]
During the interviews, the temperature and jiggling responses were overwhelming. During the meeting today @zepumph and I discussed lowering the overall amount of times these responses fired while the temperature is going down possibly even tying the responses to spots on the thermometer. But to start we should try to either lower the number of times these responses are said or increase the distance between when these responses fire.

**Comment by zepumph** [comment]
Today, @Matthew-Moore240 and I feel good about the current timing, and don't feel like it interrupts itself quite as badly anymore. @Matthew-Moore240 please reopen if you want to work on this again.
