### ISSUE TITLE
Missing Grab cue for MagnifierNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#219]
@jessegreenberg reported that the grab cue is no longer showing on startup for this Node. It is still there for the macro view.

He says that adding this line works to bring it back:

```diff
Index: js/friction/view/magnifier/MagnifierNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/friction/view/magnifier/MagnifierNode.js b/js/friction/view/magnifier/MagnifierNode.js
--- a/js/friction/view/magnifier/MagnifierNode.js	(revision 98890433374f61cecc2d7631eb18f01759b6e133)
+++ b/js/friction/view/magnifier/MagnifierNode.js	(date 1629744345593)
@@ -228,7 +228,7 @@
       objectToGrabString: zoomedInChemistryBookString,
       tandem: options.tandem.createTandem( 'grabDragInteraction' ),
       grabCueOptions: {
-        center: dragArea.center.minusXY( 0, 73 )
+        center: dragArea.center.plusXY( 0, 100 )
       },
       grabbableOptions: {
         focusHighlight: focusHighlightPath

```

Why did it break though? Perhaps something with the bounds of the Node or parent. Checking in MagnifierNode's history and didn't find anything obvious. I'll look in GrabDragInteraction next. Published version is working great though!

**Comment by zepumph** [comment]
When we set the y value at 60, it looks like this. Clearly this is from being focusHighlightLayerable, but I'm unsure when the bounds changed.

![image](https://user-images.githubusercontent.com/6856943/130503103-e9ef8749-6b1d-48c1-8583-7da6acd63ea0.png)

**Comment by zepumph** [comment]
@jessegreenberg, this looks exactly the same as the published version. I could not figure out what the original cause was. I ruled out having the draggable Node implement Voicing, and also looked through GrabDragInteraction. We converted from SimpleDragHandler to DragListener, but I'm unsure how that could have caused problems. Will you please review. Anything else here?

**Comment by jessegreenberg** [comment]
Thanks for investigating, fix looks good. It isn't clear to me either what changed to cause this.
