### ISSUE TITLE
[Voicing] onFocus "settled and cool" alert interrupted by grabbed alert 

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#227]
Promoting TODO to issue. In the description, when you grab the book, it will say "Atoms jiggle a tiny bit, temperature cool", but in voicing, the "Grabbed . . ." alert immediately interrupts this. I'm not sure how to proceed, because it seems like both are superfluous, or at least too much content when turning to the draggable. Assigning for design meeting.

**Comment by zepumph** [comment]
Discussed today during develop meeting, @terracoda and I thought that we should swap the state info and the grabbed alert, for both voicing and description, and see if that makes it so that both are spoken when the book is grabbed. I'll try that out!

**Comment by zepumph** [comment]
@terracoda, I will get you a dev version soon, then assign you to review.

**Comment by zepumph** [comment]
We want to make sure that it is realized that "onFocus" here is a bit of a misnomer, because it is when the draggable is focused. Basically you should think about it instead as "onGrab".


Please review in https://phet-dev.colorado.edu/html/friction/1.6.0-dev.14/phet/friction_all_phet.html?voicingInitiallyEnabled

**Comment by terracoda** [comment]
I will need further direction on what to do with this issue.

**Comment by zepumph** [comment]
>we discovered a bug about the jiggling-warmer response and hints are not firing optimally with mouse interaction

This is to be covered in #https://github.com/phetsims/friction/issues/234.



We are hearing "settled and cool" on grab at this point.

@terracoda wants to have one more listen. Feel free to close if all is good.

**Comment by terracoda** [comment]
The settled and cool response, "Atoms jiggle a tiny bit, temperature cool." is not being interrupted by the grab response.

Other improvements tot he experience will be tracked in other issues like #234 .

Closing issue.
