### ISSUE TITLE
Dev version feedback on split of voicing responses

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#228]
Now that https://github.com/phetsims/friction/issues/211 is complete, where object/context/hint responses were split into their voicing categories, we are ready for some more fine tuned feedback on the design and on timing. Over to @Matthew-Moore240, hopefully we can get some good progress on this before our meeting on Friday.

https://phet-dev.colorado.edu/html/friction/1.6.0-dev.13/phet/friction_all_phet.html?voicingInitiallyEnabled

Have fun!

**Comment by zepumph** [comment]
Latest and greatest: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.14/phet/friction_all_phet.html?voicingInitiallyEnabled

**Comment by Matthew-Moore240** [comment]
With all checkmarks on
- when using the mouse I hear the reset sim hint try to fire when all the atoms are gone but it gets cut off and then the sim is quiet for a few seconds and then continues to give temp information

**Comment by zepumph** [comment]
@terracoda put thoughts in https://github.com/phetsims/friction/issues/231#issuecomment-920894882

**Comment by terracoda** [comment]
@Matthew-Moore240 and @terracoda reviewed and we think the interruption and pause is related to #234. The response gets interrupted by a cooling response, but the cooling response is blank at the moment.

Let's review this after #234 8is fixed.

**Comment by zepumph** [comment]
https://github.com/phetsims/friction/issues/234 is fixed. Back to you here if it still makes sense. I added a dev version for testing. https://phet-dev.colorado.edu/html/friction/1.6.0-dev.15/phet/friction_en_phet.html?voicingInitiallyEnabled

**Comment by terracoda** [comment]
The responses seem like they are all in the correct categories.
Closing.
