### ISSUE TITLE
Update SOME_ATOMS_EVAPORATED_THRESHOLD and use it for all reset hints

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#235]
Currently SOME_ATOMS_EVAPORATED_THRESHOLD is just half of the evaporable atoms. Let's make that be all, or very close to all atoms.

Then let's use that value to determin whether or not we include the reset in `TemperatureIncreasingAlerter.maxTempUtterance`. This will give more continuity to that hint, and decrease the number of times we hear that before we should.

**Comment by zepumph** [comment]
@terracoda please review. I made it such that there is no reset hint until all atoms possible have evaporated.

**Comment by terracoda** [comment]
I like the threshold at 100%

However, I just realised that a better place for the dynamic hint would be at the end of the cooling, after all possible atoms have broken away.

I find it quite annoying to keep hearing "Reset sim to make more observations" as the sim cools. 

I am not actually hearing the cooling responses, maybe this will change once we address the cooling response issue #234 

The threshold is good!

Would it be possible to tie the hint onto a response that doesn't repeat? For example, the final cooling response? 

Before all atoms have broken away:
- Atoms jiggle a tiny bit, temperature cool.

After all atoms have broken away and the sim reaches its steady state:
- Atoms jiggle a tiny bit, temperature cool. Reset sim to make more observations.

Is relocating the string something we can do easily?

**Comment by terracoda** [comment]
I'll close this issue and open a new one to look at after #234 is address.
