### ISSUE TITLE
Changes to the content for "The Overview" Button

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/friction#238]
Please change the content of the "The Overview" button to:

_{{Friction}} is an interactive sim. It changes as you play with it. Get ready for Friction, there’s a stack of big textbooks ready to go. In zoomed-in view of textbooks you can observe how jiggling atoms and temperature changes._

**Comment by terracoda** [comment]
Apologies, I think I have a typo in that new over.

The final "s" is not needed.

{{Friction}} is an interactive sim. It changes as you play with it. Get ready for Friction, there’s a stack of big textbooks ready to go. In zoomed-in view of textbooks you can observe how jiggling atoms and temperature change.

**Comment by zepumph** [comment]
Done above

>Friction is an interactive sim. It changes as you play with it. Get ready for Friction, there’s a stack of big textbooks ready to go. In zoomed-in view of textbooks you can observe how jiggling atoms and temperature change.
