### ISSUE TITLE
(Voicing & PDOM) Consider re-locating reset string

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#240]
In #235, I commented

> However, I just realised that a better place for the dynamic hint would be at the end of the cooling, after all possible atoms have broken away.

> I find it quite annoying to keep hearing "Reset sim to make more observations" as the sim cools.

> I am not actually hearing the cooling responses, maybe once we address the cooling response issue #234, I won't hear the "super-fast-rest" string keep repeating.

> Again, the threshold is good!

> Would it be possible to tie the hint onto a response that doesn't repeat? For example, the final cooling response?

> Before all atoms have broken away:
> Atoms jiggle a tiny bit, temperature cool.

> After all atoms have broken away and the sim reaches its steady state:
> Atoms jiggle a tiny bit, temperature cool. Reset sim to make more observations.

> Is relocating the string something we can do easily?

Once we fix #234, I would like to review this question.

**Comment by terracoda** [comment]
@Matthew-Moore240 and @zepumph, mentioning you so this issue is on your radar, but no action required right now.

**Comment by zepumph** [comment]
@terracoda, @Matthew-Moore240, and I discussed this today. By moving the reset alert from the break away to the "temperature cool" alert. We like it after this because it is at the complete end of an interaction. I also don't think it will be hard to implement. Yay!

**Comment by zepumph** [comment]
Ok, this move was easy, and I really like it. There is one more case where we are getting this hint with the settled and cool alert, and I really like it.

When we grab the book, and the temp is settled and cool, we are now saying reset the sim. This is because that logic is shared with the default "settled and cool" alert, but I think we could change it if we had to. But I'd rather not unless there was a reason.

**Comment by Matthew-Moore240** [comment]
Reviewed with @terracoda and @zepumph, it sounds really good. Closing.

**Comment by terracoda** [comment]
@zepumph, there is a little more work to do here. I hear the reset hint after I reset the sim. Can you have a look?

**Comment by terracoda** [comment]
I hear the reset in description and voicing.

**Comment by terracoda** [comment]
In https://github.com/phetsims/friction/issues/240#issuecomment-926775974
@zepumph said

> When we grab the book, and the temp is settled and cool, we are now saying reset the sim. This is because that logic is shared with the default "settled and cool" alert, but I think we could change it if we had to. But I'd rather not unless there was a reason.

We have to restrict the reset hint to when there are no more atoms that can be vaporized. After initial implementation, I got the reset hint at the end of the settled cooled state on my initial grab after a full reset. And I also saw it in the interactive description design after a full reset.

I can check again. Maybe you fixed that.

**Comment by terracoda** [comment]
I don't hear the reset hint on first grab before interaction.

I hear it on the first grab after a reset.
![Screen Shot 2021-09-28 at 3 52 38 PM](https://user-images.githubusercontent.com/1902116/135144010-3c1f9e76-8efe-4f84-a93e-262f5c5e8abd.png)

**Comment by terracoda** [comment]
The same for Voicing. No hint on initial grab before interaction begins, but I hear the reset hint on initial grab after I evaporate all atoms and do a full reset.

**Comment by terracoda** [comment]
I am using the latest version on phettest.

**Comment by zepumph** [comment]
Thanks for the testing. 

I was before updating the hint whenever the amplitude (temperature) changes. In the case of reset, when the temp is already cool, there is no change, so I will update every time right before alerting.

**Comment by zepumph** [comment]
How about that?

**Comment by terracoda** [comment]
Re-assigning to @Matthew-Moore240. @Matthew-Moore240, let me know if you need any clarification from me.

**Comment by Matthew-Moore240** [comment]
Issue fixed. Closing
