### ISSUE TITLE
"Rub fast or slow" each time a level of atoms breaks away and you move down to make contact again.

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#244]
Steps to reproduce:
1. with mouse, move down to contact books
2. correctly hear "rub fast or slow" hint
3. in a very horizontal way, make one row of atoms shear, thus the books are no longer contacting.
4. Move down to contact books again.
5. Weirdly hear again "rub fast or slow" instead of other alerts like warmer or break away alerts. Isn't this superfluous because the user already successfully interacted with it?

This is a bit strange. I wonder if this hint would make sense to only do if there were 0 atoms sheared off? Otherwise presumably they know how to make friction.

Over to designers

**Comment by terracoda** [comment]
@zepumph, thanks for posting this case. I had also noticed it, and felt it wasn't ideal, but wasn't sure how to address it. 

I also noticed that productive rubbing on a diagonal can trigger both rubbing hints (rub fast or slow and move down to rub harder), though the move down hint seems to get uttered less often. This case is also not ideal after a successful break away.

I think your idea sounds good. It would tie the "Rub fast or slow" hint more closely to unproductive rubbing which is what both hints were designed for. 

I think your idea means we would hear "Rub fast or slow" each time the books meet BEFORE there is a successful break away event (and of course after a full reset), and then not hear it each time the books meet after that successful break away event? I think this would work well.

I'll also point out that the sonification (i.e. the bump sound) scaffolds productive rubbing, and we hear that rub reminder every time the books meet. Hearing the hint "Rub fast or slow" is  meant to get folks going and not keep them going. The warming and cooling responses should keep them going until all atoms have evaporated.

**Comment by terracoda** [comment]
I think @Matthew-Moore240 would agree. @Matthew-Moore240, please comment with any additional thoughts or concerns. If you would like to proceed with @zepumph's idea please change label to dev-a11y and assign issue to @zepumph.

**Comment by zepumph** [comment]
>I also noticed that productive rubbing on a diagonal can trigger both rubbing hints (rub fast or slow and move down to rub harder), though the move down hint seems to get uttered less often. This case is also not ideal after a successful break away.

I created https://github.com/phetsims/friction/issues/245 to fine tune.

This issue is to discuss the logic about when the hint will play (and when it won't).

**Comment by Matthew-Moore240** [comment]
This seems good to me.

**Comment by zepumph** [comment]
This was sounding really nice to me! What do you think @Matthew-Moore240?

**Comment by Matthew-Moore240** [comment]
This sounds nice to me as well. Closing.
