### ISSUE TITLE
Review Description and Voicing strings for PhET-iO

### ISSUE THREAD

**Issue by arouinfar** [phetsims/friction#251]
Related to #236 

In PhET-iO meeting we decided that I should review the description and voicing strings in Friction to identify if there are any strings that could becoming inaccurate/out-of-sync with PhET-iO customization.

For example, clients can change the name of the Chemistry book using `view.topBookNode.titleText.textProperty`. However, "Chemistry" appears throughout the description and in the name of other UI elements, such as buttons.

Voicing strings can be printed to the console using the `printVoicingResponses` query parameter.

**Comment by terracoda** [comment]
Thanks for opening this issue @arouinfar.

Some description strings not meant for Interactive Description and some behaviours of hints that may be problematic for non-visual users need some review, too. I will open a seperate issue about that.

**Comment by arouinfar** [comment]
The goal of this issue was to survey Description and Voicing strings that could be impacted by PhET-iO customization. That's been done, so I don't think we need to keep this issue open, so closing.
