### ISSUE TITLE
"Move down" hint is only needed before productive rubbing

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#252]
Similar to https://github.com/phetsims/friction/issues/244, we don't need to hear "move down to rub harder" beyond the initial time it takes to train the user.

Unlike with "rub fast or slow" I think it is still important to potentially hear this after a the first row of atoms break away, so that they realize that you need to have to move down and then keep rubbing.  After a few rows though, we shouldn't muddy the waters with this alert.

**Comment by zepumph** [comment]
Marking for meeting tomorrow to co-review and hopefully close.

**Comment by Matthew-Moore240** [comment]
Check issue with keyboard and mouse.
Idea from Taliesin: 
If temp is increasing you shouldn't hear the hint.

**Comment by zepumph** [comment]
>Idea from Taliesin:
If temp is increasing you shouldn't hear the hint.

This only requires investigation if @Matthew-Moore240 finds trouble with the current implementation. Otherwise @Matthew-Moore240 will just close this issue after testing on the other platforms/modes listed above.

**Comment by Matthew-Moore240** [comment]
No issues with just hearing the "move down" alert on initial unproductive rubbing before any breakaways happen. Closing
