### ISSUE TITLE
"Super fast, super hot" piles up way too much

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#253]
This is mainly for description, because voicing is interrupting much more. That said it can still happen with Voicing.

Some thoughts from a meeting with @Matthew-Moore240 and @terracoda:

* It would be really nice to not have repetition of this max temp alert
* It would be really nice to not just have the last one. 
* Let's mess with timing variables to try to get the max temp alert to alert less often than the warming alert. 

I think we should convert `tooSoonForNextAlert` to use Utterance timing options instead.

This came from testing in https://github.com/phetsims/friction/issues/243, and this needs to be fixed before more testing can occur over there.

**Comment by zepumph** [comment]
- [ ] please make a dev link when this issue is complete.

**Comment by terracoda** [comment]
@zepumph comment 

> This is mainly for description, because voicing is interrupting much more. That said it can still happen with Voicing.

in https://github.com/phetsims/friction/issues/253#issue-1013555285

That hasn't been my experience. I got the major pileups in Voicing last Friday in our meeting.

**Comment by terracoda** [comment]
If I rub relativley slowly to super fast, I don't get a pile up, but if I rub quickly to super fast I get a pile up. I can demo in the meeting.

**Comment by zepumph** [comment]
During voicing meeting today, I realized that we could use the Utterance predicate to determine if the "super hot" still applies before announcing it.

**Comment by zepumph** [comment]
Ok. I have cleaned this up with a couple of pieces of logic.

1. "super fast" alerts now occur less often, as I split up the timing variable shared with it and the warming utterance. Now it is only every 3 seconds (instead of 1/2 second).
2. I added predicates to both utterances that make sure that their logic is correct before we do announce it. This helped greatly with the number of max-temp alerts we get, but https://github.com/phetsims/scenery/issues/1294 will further assist because sometimes we have already announced multiple versions of the utterance.
3. I added logic that clears the utteranceQueue of all utterances when the thermometer is full, and you end your drag. This will hopefully signal the end of an interaction, and get rid of warming/max-temp alerts.

@terracoda please review.

**Comment by Matthew-Moore240** [comment]
Yeah, the mouse is working nicely. No more pile-ups.

**Comment by Matthew-Moore240** [comment]
It sounds perfect to me. No pile-ups and no extra super hots or super fast. Closing.
