### ISSUE TITLE
(Interactive Description) I hear "Move down to rub harder" before I try to rub

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#257]
This hint has to be linked to unproductive rubbing.
It is now working well in Voicing, but not yet working well in on grab when using VoiceOver on MacOs and keyboard.

I do get the hint BEFORE and after non-productive rubbing.

This issue might resolve itself, but the design goal is to only get this hint when unproductive rubbing is occurring and not immediately as part of the grab when the books are apart.

**Comment by zepumph** [comment]
>I do get the hint BEFORE

This is true, but I think incomplete.

**The way it was:**

The "move down to rub harder" alert for pdom alerts was added on if the books weren't touching AND there had been successful rubbing. I was able to get this alert to fire when I made successful rubbing, then made the books not touch, released the book, and then grabbed it again.


**After my commit**

I have completely removed this hint from the grabbed alerts in the PDOM. Instead, you will only get them based on logic that looks at how you are rubbing, and if you rub too much without touching the books. @terracoda please review.
