### ISSUE TITLE
(Voicing) Can we optimize responses with alt input keyboard?

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#258]
In #242 and #253 and other issues we improved the experience greatly for both mouse and keyboard.

I feel a second look at optimizing the alt input keyboard experience would be good, if there is time.

In #253 I mentioned 2 specific issues.
1. often an extra super fast, super hot response after rubbing stops, and
2. rare occurrences (possibly no occurrences) of "jiggling more, warmer" as temperatures increase.

**Comment by zepumph** [comment]
@terracoda was using smaller key presses than I was. I'll take a look.
