### ISSUE TITLE
Voicing reads line break in keyboard dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#261]
**Test device**
MacBook Air (m1 chip)

**Operating System**
iOS 11.6

**Browser**
safari 15

**Problem description**
https://github.com/phetsims/qa/issues/717

The line break element is read with Voicing in the 'Grab or Release Book' section of the Keyboard Shortcuts Dialog. 

**Steps to reproduce**
1. Turn Voicing on
2. Open Keyboard shortcuts dialog
3. Tab to or click on 'Grab or Release Book' section

**Visuals**

https://user-images.githubusercontent.com/87318828/137138687-8516ef1f-2d93-4cd1-b5ad-c9e659e50087.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.19/phet/friction_all_phet.html
Version: 1.6.0-dev.19 2021-10-08 22:59:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1440x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Right, thanks! I'll take the lead over in https://github.com/phetsims/scenery/issues/1314.

**Comment by zepumph** [comment]
Just waiting on review over in https://github.com/phetsims/scenery/issues/1314.

**Comment by zepumph** [comment]
Alright, review is complete. @Nancy-Salpepi can you confirm this is fixed on master please?

**Comment by zepumph** [comment]
Feel free to close.

**Comment by Nancy-Salpepi** [comment]
This is fixed :)
Closing.
