### ISSUE TITLE
Voicing skips over portion of 'Move Book' section in keyboard dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#262]
**Test device**
MacBook air (m1 chip)

**Operating System**
iOS 11.6

**Browser**
safari 15

**Problem description**
https://github.com/phetsims/qa/issues/717

Voicing skips over 'Move Slower' keyboard keys in keyboard dialog.

**Steps to reproduce**
1. Turn on voicing
2. Open Keyboard Shortcuts dialog
3. Tab to or click on 'Move Book' section

**Visuals**

https://user-images.githubusercontent.com/87318828/137140833-9fef66a3-782a-4a80-b282-e1f42817fbbe.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.19/phet/friction_all_phet.html
Version: 1.6.0-dev.19 2021-10-08 22:59:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1440x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
This was fixed by https://github.com/phetsims/scenery-phet/issues/711, out for review now.

**Comment by Nancy-Salpepi** [comment]
The entire keyboard shortcuts dialog is now read with Voicing.
I did notice that there is no pause at all after the "D" in WASD and  "Move Slower". I tried on both safari and chrome with my mac and with 3 different voices.



 

https://user-images.githubusercontent.com/87318828/155597924-d5dd716d-ecba-41f9-9cf2-00380dde72b4.mov

**Comment by zepumph** [comment]
I hear that too! When I use `?printVoicingResponses` this is what is being spoken:

>Move Book, Move grabbed book or zoomed-in book up, left, down, or right with Arrow keys, 
or with letter keys W, A, S, or D. Move slower with Shift plus Arrow keys, or Shift plus letter keys W, A, S, or D. 


I see the period there. Voices are sometimes weird, but I think we are doing the best we can. Closing
