### ISSUE TITLE
Should Voicing continue with sim descriptions after preferences menu is opened?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#263]
**Test device**
MacBook Air (m1 chip)

**Operating System**
iOS 11.6

**Browser**
Safari 15

**Problem description**
https://github.com/phetsims/qa/issues/717

After the Preferences Menu is opened, Voicing continues to report changes happening in sim. 

**Steps to reproduce**
1. Turn on voicing and check all checkboxes
2. Quickly rub chemistry book back and forth on physics book
3. While descriptions are happening, click on Preferences Menu

**Visuals**

https://user-images.githubusercontent.com/87318828/137155236-5aff6052-7811-4fb3-93ce-b0e3460ea5b3.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.19/phet/friction_all_phet.html
Version: 1.6.0-dev.19 2021-10-08 22:59:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1440x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by terracoda** [comment]
I think the work in https://github.com/phetsims/joist/issues/752 is working well. 

At this point (June 29, 2022) there is a nice balance between what is happening in the background and any interactions the user is taking in an opened preferences dialog. 

I think this issue can be closed.

**Comment by zepumph** [comment]
Excellent! I think so too
