### ISSUE TITLE
Issue when 2 buttons are pressed at same time on iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#266]
**Test device**
iPad Air 2 (name: Leibniz)

**Operating System**
15.0.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/717

On the iPad:
When the reset button is pressed at the same time as one of the 'Read Me' buttons, the sim will reset. However, the 'Read Me' button will look like it is in play mode--a STOP symbol is present. If reset is pressed again, the button will not change back to a PLAY symbol. 

**Steps to reproduce**
1. Turn on voicing
2. Toolbar option should be on
3. Press the reset button and any of the 'Read Me' buttons at the same time. 

**Visuals**

https://user-images.githubusercontent.com/87318828/137532925-b905fe35-a665-4394-9c98-414cd9e83475.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.19/phet/friction_all_phet.html
Version: 1.6.0-dev.19 2021-10-08 22:59:15 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1024x1224
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
These buttons switch back to the "play" icon from the voicingManager.endSpeakingEmitter so my first guess is that that emitter is not being emitted for some reason.

**Comment by emily-phet** [comment]
This seems like a relatively minor usability issue to me. If @jessegreenberg finds this to be relatively straightforward to fix, or relatively straightforward to identify as a browser bug, then let's fix it in the case of it not being a browser bug. If it's a browser issue or a fix that's likely to delay publication, then I don't think this should be blocking for publication of Friction.

**Comment by zepumph** [comment]
Today during voicing meeting we decided this won't block friction, @jessegreenberg will investigate for https://github.com/phetsims/scenery/issues/1315.

**Comment by jessegreenberg** [comment]
I suspect this has been fixed with https://github.com/phetsims/utterance-queue/issues/66. I tried to get the original issue to happen on my iPad Air 2 and could not. @Nancy-Salpepi if you have a moment can you please test?

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg sometimes when both buttons are pressed at the same time, I hear the 'Reset All' sound and voicing either says "reset all" and then reads the Quick Info statements or reads the statements and then says "reset all".

I was not able to reproduce the original issue. 

Videos:
<details>

https://user-images.githubusercontent.com/87318828/159009277-15412a16-b4db-4f26-b77b-f429494c5edb.mov


https://user-images.githubusercontent.com/87318828/159008592-8cd037e0-cd93-41a8-ac38-9578467bcb60.mov

</details>

**Comment by zepumph** [comment]
None of the above videos seemed like a bug to me. I think it is reasonable that you could hear one or both of the responses depending on how things end up in the queue. I don't think it is worth looking into this edge case any more. I'm going to close. Please reopen if you feel differently.
