### ISSUE TITLE
(Description) Duplication of name and custom role in Grab/Drag Interactions

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#271]
I see the following code in the inspector, and I think there is too much repetition of "Movable Chemistry book" in this interaction. 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/1902116/147927971-6c01cd67-9c6f-4afc-9d8f-138997f4de8b.png">

When using VoiceOver, I hear the following on grab:
- Movable Chemistry book, empty Movable Chemistry book" then "Grabbed. Lightly on Physics book..."

Ideally, I should only hear:
- Chemistry book, empty movable" then "Grabbed. Lightly on Physics book..."

I think to fix this issue we need to do the following:
1. change the object names in both the `aria-label` attributes and the content of the draggable `div` elements to:
    - `aria-label="Chemistry book"` and `aria-label="Zoomed-in Chemistry book"`
    - "Chemistry book" and "Zoomed-in Chemistry book"
2. change the custom role to `aria-roledescription="movable"` in both cases. 

I do not hear this level of repetition in the case of the grabbed "Ruler" in Gravity Force Lab nor in the case of the grabbed "Bar Magnet" in Faraday's Law. In Balloons and Static Electricity, it is hard to tell because of timing differences, but I think the balloons are coded as above. 

I think this is a common code interaction, so it's possible Friction has not been updated to the final common code? Please check on that. (edit) Please check in case there is some reason why we have done this interaction differently in Friction.

**Comment by zepumph** [comment]
@terracoda, I wonder, were you testing on the published version? In master this is what I see when I grab the macro book:

![image](https://user-images.githubusercontent.com/6856943/151043363-2ac073d7-70b2-4b19-913b-3eb80b22a944.png)

We did quite a bit of work in the common code of GrabDragInteraction when doing it for the Ruler in ISLC, so it is quite possible that much of what you were talking about is already in master.

When I test with NVDA I hear: "Chemistry book, movable" the "Grabbed, lightly on physics book"

**Comment by zepumph** [comment]
I created https://phet-dev.colorado.edu/html/friction/1.6.0-dev.23/phet/ so you can test more easily.

**Comment by terracoda** [comment]
I don't hear duplication any more in the link you gave me.
https://phet-dev.colorado.edu/html/friction/1.6.0-dev.23/phet/

**Comment by zepumph** [comment]
Friction is set to be published this quarter, so hopefully we will have this fixed in production soon!
