### ISSUE TITLE
Grabbed book can't be moved up/down with mouse

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#276]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/791, I noticed that I can no longer move the chemistry book up and down like in published. Now clicking on the book immediately changes the zoomed in view so that the 2 books are touching. 
I am still able to move the grabbed book up and down with keyboard nav. 

**Steps to reproduce**
1. Click on the chemistry book and try to move it up and down.

**Visuals**

https://user-images.githubusercontent.com/87318828/160884497-f0c8b40c-e505-4d65-8655-05fcdcf59cfb.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet/friction_all_phet.html
Version: 1.6.0-dev.24 2022-03-30 15:06:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I was able to lift the book with a mouse, but you have to move your mouse well above any point where it feels natural.
![wayup](https://user-images.githubusercontent.com/41024075/160906450-dadde866-4922-4958-9984-ac1339263da0.gif)

**Comment by KatieWoe** [comment]
It also jumps the book oddly far to the right as well as down.

**Comment by zepumph** [comment]
Yes sorry about that. This was a bug from a while ago that I wasn't able to fix until right now. Using the parent offset solved this, and I also factored out the transform for the macro book to a Transform3 for clarity and documentation. Closing
