### ISSUE TITLE
Extra interactive highlights

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#277]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/791 there seems to be extraneous interactive highlights--a pink line appears across the entire screen and the physics book also has one.

**Steps to reproduce**
1. Turn on interactive highlights
2. Move mouse around the screen and over different objects

**Visuals**

https://user-images.githubusercontent.com/87318828/160886289-f04655e8-af57-47ca-b37d-af1a21805469.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet/friction_all_phet.html
Version: 1.6.0-dev.24 2022-03-30 15:06:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
It has been a while here, but this should not be fixed. Can you please confirm. There should no longer be an interactive highlight around the entire, huge, magnifierNode, and also around the physics book (which isn't interactive either).

**Comment by Nancy-Salpepi** [comment]
@zepumph I no longer see the interactive highlights around the entire magnifierNode or physics book in the PhET brand sim or PhET-iO standalone sim. 
When I tried to turn on interactive highlights in studio, there was an assertion error which froze studio. 
<img width="621" alt="Screen Shot 2022-06-04 at 7 05 22 AM" src="https://user-images.githubusercontent.com/87318828/171996605-c084ae05-eb38-49f8-b70f-422acf9c7779.png">
