### ISSUE TITLE
Launched sim freezes with safari

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#278]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/791
When I try to interact with the launched sim in safari, it freezes. After a delay the 'releasing book' sound is heard. When I return to the Studio wrapper it also looks odd and takes a few seconds to return to normal. 

* this did not happen with mac + Chrome
* this also occurred in Master ( I tried other sims in Master and while Studio took a while to open, no freezing occurred) 
* Nothing came up in the console
* @KatieWoe was also able to reproduce this problem so it is not device specific. 

**Steps to reproduce**
1. Launch the sim from studio
2. Attempt to move the book.
3. Go back to the studio wrapper

**Visuals**

https://user-images.githubusercontent.com/87318828/160917444-d1e30d22-c1a0-4638-bc8d-04c2ccf1691b.mp4

**Comment by KatieWoe** [comment]
I reproduced this on iPad by launching the example sim

**Comment by Nancy-Salpepi** [comment]
In studio with safari --the preview HTML worked properly.

**Comment by KatieWoe** [comment]
This also happened when trying to record on iPad with Metacog recording.

**Comment by KatieWoe** [comment]
It's still happening in master. I didn't see a console error there either.

**Comment by zepumph** [comment]
Sam has a mac, and I solicited his help here. Thank you!

**Comment by samreid** [comment]
I tested Safari Version 15.2 (17612.3.6.1.6) on MacOS Monterey 12.1, and launched https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet-io/wrappers/studio/ then pressed "preview sim" then moved the book and went back to studio. Everything continued to behave as expected.

**Comment by zepumph** [comment]
@Nancy-Salpepi can we please schedule some time to pair on this. I think next steps would be to try to reproduce on the original machine. Thanks for testing @samreid!

**Comment by Nancy-Salpepi** [comment]
Sure @zepumph! I am around tomorrow. Let me know what works for you.

**Comment by samreid** [comment]
I was not able to reproduce this problem or https://github.com/phetsims/gravity-and-orbits/issues/421 on Safari Version 15.2 (17612.3.6.1.6) on MacOS 12.1.

I was able to reproduce this on my iPad 15.5 and iPhone 15.4.1.  After updating both to 15.6, I am not able to see the problem any more on either of those devices after many tests.  I also updated my macOS to get Safari 15.6 and still cannot see the problem there.  So the hypothesis is that Safari introduced a bug between 15.3 -> 15.5 and fixed it in 15.6.  @Nancy-Salpepi do you have Safari 15.6 devices you can test, or can you update your 15.5 safaris for a test?

**Comment by Nancy-Salpepi** [comment]
@samreid I will update everything now and see if I can reproduce.

**Comment by samreid** [comment]
@marlitas tested on Safari 15.5 and saw the problem twice (at about 4 seconds each).

**Comment by Nancy-Salpepi** [comment]
@samreid After updating to Safari 15.6 I wasn't able to produce the problem (0/4), even with clearing history each time.

**Comment by zepumph** [comment]
Awesome! Thanks for the hard work everyone.
