### ISSUE TITLE
Steam hiss may play in State even when option is not on

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#279]
**Device**
Mac and iPad (but not able to reproduce so far on Win 11)
**OS**
MacOS 12.3 and iPadOS 15
**Browser**
Safari and Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/791
When in the state wrapper, if you move the bottom sim while the temp is dropping, then it will start playing the hissing sound as temp drops, even when that option isn't on
Steps to Reproduce
1. Go to State wrapper on an Apple device
2. Make sure extra sounds are off
3. Set the refresh rate to about 3500. Other values work, but I found around this value easiest
4. In top sim, create a high temp and let it start to drop
5. In bottom sim, when state updates and it has a dropping temp, move the book in bottom sim to raise temp again
6. When state updates again, the hissing sound will occur and will continue to happen even without the setup

**Visuals**

https://user-images.githubusercontent.com/41024075/160922611-c34c2e22-7af0-4c35-a8b4-c214ba8d3e7e.MOV

**Comment by KatieWoe** [comment]
I take this statement back:
>(but not able to reproduce so far on Win 11)

I have gotten it to occur on Win 11

**Comment by stemilymill** [comment]
On Win10 Chrome, the sim launched from studio plays the hiss when extra sounds are turned off

**Comment by zepumph** [comment]
This has been fixed by removing the "extraSoundsEnabledProperty" from state. Can you please confirm this is fixed on master and feel free to close.

**Comment by KatieWoe** [comment]
It seems fixed on master. I wasn't able to replicate it on Win 11 chrome. Will reopen if it shows up again.
