### ISSUE TITLE
Can drag chemistry book out of play area on iPad 

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/friction#28]
I noticed it is possible to drag the chemistry text book out of the magnified play area while the iPad is in landscape mode. This is a minor issue as one can use the reset button.

To reproduce:
Remove all particles off of the text book
Drag textbook to the top left hand of the screen
You will lose the touch area and cannot drag the text book back

Troubleshooting information (do not edit):
Name: Friction
URL: http://www.colorado.edu/physics/phet/dev/html/friction/1.1.0/friction_en.html
Version: 1.1.0
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 53.13)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true

**Comment by jbphet** [comment]
fixed, closing
