### ISSUE TITLE
Difficult to grab zoomed in book when located at top of window

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#281]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/791
After atoms have been rubbed off, it can be difficult to grab the zoomed in book when it is at the top of the window. When interactive highlights are on, I can see that grabbing the space will result in me grabbing the book. When they are off, it is my instinct to grab the atoms and I can't. In the published version, I am able to grab the atoms. 

**Steps to reproduce**
1. Move zoomed in book to rub off all the atoms.
2. Move zoomed in book to top of window and release.
3. Try to grab zoomed in book. 

**Visuals**
Dev version:

https://user-images.githubusercontent.com/87318828/161065663-35c87bca-7f96-4c8e-8f8f-f04ee064ea78.mp4

<br>
Published version:

https://user-images.githubusercontent.com/87318828/161065772-2f86f0b0-200e-4b85-8776-fc5cdf0934b9.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet/friction_all_phet.html
Version: 1.6.0-dev.24 2022-03-30 15:06:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I noticed that, in the dev test, the bubbles in the row attached to the book are not grabbable. This is not the case for the published sim, which seems to worsen the problem now compared to previous versions.

**Comment by zepumph** [comment]
Very helpful bug report. The regression was in the little bumps on the background blue. Should be fixed, please confirm and feel free to close.

**Comment by Nancy-Salpepi** [comment]
Looks good! Closing.
