### ISSUE TITLE
Voicing with Safari reads period as "dot" in licensing section of PhET-iO About Dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#282]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/791, in the PhET-iO sim, Voicing reads the period as "dot"  in the licensing section of the About dialog. It does this for the first 2 sentences, but not for the last sentence in that section. 

* This does not occur anywhere else in the sim where there is a period (preferences dialog, 'Thanks' section of the About dialog)
* This does not occur with Mac + Chrome
* This does not occur anywhere in the PhET brand sim 

**Steps to reproduce**
1. Using Safari, Turn on Voicing in the PhET-iO brand sim.
2. Read through the About dialog in the PhET menu.

**Visuals**

https://user-images.githubusercontent.com/87318828/161116762-59823a9d-bdbb-43d7-bf9e-501d6859afbd.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet/friction_all_phet.html
Version: 1.6.0-dev.24 2022-03-30 15:06:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
I'll look at what the voicing string looks like and see if it is weird.

**Comment by zepumph** [comment]
I can't seem to load the sim on my iPad right now, but my best guess here is that it has to do with when we use <br> tags in RichText.

**Comment by zepumph** [comment]
I just tried this on iPad os 15.6 and couldn't reproduce. @Nancy-Salpepi do you mind double checking on your end? Feel free to close.

**Comment by Nancy-Salpepi** [comment]
@zepumph I can still reproduce this on my MacBook Air (macOS 12.5.1 + Safari 15.6.1) and on my desktop (macOS 10.15.7 + Safari 15.6.1).
I was not able to reproduce this issue on the iPad either.

**Comment by zepumph** [comment]
We found that our voicing code was incorrectly replacing a `<br>` tag with nothing, where instead it should have been adding a space to things. Solved above in https://github.com/phetsims/utterance-queue/commit/2c543b0d42d657b48f98690e6530ad69d9c68157. @Nancy-Salpepi can you please confirm things are fixed and feel free to close.


I also wanted to note that we were able to reproduce the bug with the "Alex" voice on safari, but not with "Samantha". Given this, in the future, it may be helpful for QA to provide the voice that a bug occurred with when a bug is related to voicing.

**Comment by Nancy-Salpepi** [comment]
Looks good in master. @zepumph I will add a line in the QA book about noting the voice used when making issues and will mention at QA meeting tomorrow.
