### ISSUE TITLE
Voicing with Safari only works in one iframe in Multi wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#283]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/791
The voicing feature only works in the second iframe. It doesn't work in the first one. 

This issue was not seen in mac + chrome or on Win10 + Firefox.

**Steps to reproduce**
1. Turn on voicing in the preferences menu--It will say Voicing on
2. Press or move anything else--no voicing is heard

**Visuals**

https://user-images.githubusercontent.com/87318828/161124948-fc6a00e0-89d2-417d-9d40-04e9c1562df3.mov

**Comment by KatieWoe** [comment]
I'm also noticing that it doesn't work in State on the top iframe on iPad either.

**Comment by zepumph** [comment]
@jessegreenberg and I couldn't reproduce this issue in 15 minutes on a mac 11.6 + safari 15.2. We feel ready to close given our current level of support for voicing + phet-io. Thanks for the report.

**Comment by Nancy-Salpepi** [comment]
For https://github.com/phetsims/qa/issues/868
Noting that I still see issues with Voicing working in multiple iframes with Multi and State wrappers. I am on macOS 13.0.1 and safari 16.1.
