### ISSUE TITLE
Disabling an object removes it from voicing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#287]
**Device**
Dell
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/791
In studio, if you disable interaction on an object, such as the zoomed out book so the user must use the zoomed in book, clicking on the disabled object with voicing does not read anything out. In addition, noting is read out when clicking the physics book, which seems wrong, especially as the mouse indicates that it is interactable.

**Comment by Nancy-Salpepi** [comment]
@KatieWoe--For the last part of your comment (nothing is read out when clicking the physics book), I think this is related to the issue I posted https://github.com/phetsims/friction/issues/277.

**Comment by zepumph** [comment]
This is unfortunate, and expected. We won't have this capability until we do https://github.com/phetsims/scenery/issues/1220 (currently deferred). Closing as won'tfix.
