### ISSUE TITLE
Should bottom book text be non-customizable?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#290]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/791, in studio if I change the name of the bottom textbook (`friction.frictionScreen.view.bottomBookNode.titleText.textProperty`), Voicing still reads it as "Physics". Should this text still be customizable?

**Comment by zepumph** [comment]
This is true, but it is expected, it is still worth customizing the text, and this amount of synchronous updates is what we will continue to strive for with voicing/description + PhET-iO, but not in Friction.
