### ISSUE TITLE
Changes required after the addition of canAnnounceProperties

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#298]
After https://github.com/phetsims/scenery/issues/1403 changes are coming to Alerter.ts and Voicing.ts which may require implementation changes in the sim. This issue is to track and review.

**Comment by jessegreenberg** [comment]
OK, this transition is done. In https://github.com/phetsims/friction/commit/379e614788c2bdbccb344696435a63d7b90b01ab the `Alerter` `Utterances` were registered to the `chemistryBookNode` because it was required to register them to a `VoicingNode` with a `voicingCanSpeakProperty`.

Later in https://github.com/phetsims/scenery/issues/1403 I added a `registerUtteranceToNode` which can link to a `voicingVisibleProperty` so that we can register `Utterances` to the `ScreenView` which is something we thought was beneficial in https://github.com/phetsims/scenery/issues/1403#issuecomment-1098436757.

The `Utterances` are coming through as I would expect with the "Sim Voicing" toggle in the toolbar. @zepumph this is ready for you to verify.

**Comment by zepumph** [comment]
Awesome, thanks!
