### ISSUE TITLE
Some weirdness with the Chemistry Book interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#299]
On master using Safari on MacOS 12.2.1 I just noticed that the grabbing of the Chemistry book does not allow me to move up. It's always against the Physics book.

The Zoomed-in Chemistry book seems fine.

I have not done a deep dive, just noting I saw an issue.

**Comment by terracoda** [comment]
The issue is with mouse input not keyboard input.

**Comment by terracoda** [comment]
The issue exist on mobile, too. I am now using iOS 15.5 on iPhone 7.

**Comment by zepumph** [comment]
This is my fault, I'll solve it in Friction code, we don't need to change the aria for this issue.

**Comment by zepumph** [comment]
Duplicate with https://github.com/phetsims/friction/issues/276, fixed above.
