### ISSUE TITLE
strings aren't scaled to fit on books

### ISSUE THREAD

**Issue by jbphet** [phetsims/friction#30]
The long string test fails, looks like this:

![friction-string-issue](https://cloud.githubusercontent.com/assets/3082831/10623300/341c4764-774b-11e5-83e0-e0d863c6e87a.png)

**Comment by phet-steele** [comment]
This is looking A-OK on Win 8 FF (1.2.0-rc.2) :+1:

**Comment by jbphet** [comment]
Fixed, closing.
