### ISSUE TITLE
Hear hints to use keyboard in drag/grab interactions on first grab when using mobile VO

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#307]
While investigating #294, I found that on the first grab of either book interaction, I got a rubbing hint that included pressing hot keys (A & D for the regular book and WAS&D for the zoomed-in book). 

I think there should be an option (already implemented in common-code) to use a mobile-specific hint once a grab/drag interaction is activated on mobile. Or possibly there is no mobile specific hint needed, since the user just needs to keep their finger down and rub after a successful double tap & hold. Regardless, I should never hear anything about pressing keyboard keys when using mobile. The keyboard instructions are platform specific.

This issue happened twice for me during testing.
I think it only happens on the first successful grab.

**Comment by zepumph** [comment]
Looks like we just never created touch/gesture hints for this case. You are right they are only on the first grab. "Subsequent" grabs after successfully making friction won't have this.

I took a first pass at them, please review and let me know what actual strings you want here:

https://github.com/phetsims/friction/blob/6c1d0b5029303b62ef0eab12ab64c5fbcf57ab4b/friction-strings_en.json#L42-L53

**Comment by zepumph** [comment]
@terracoda and I discussed. We feel good about the above description. Closing.

**Comment by terracoda** [comment]
The hints sound great on mobile VO! Awesome work! Thanks!
