### ISSUE TITLE
Dynamic scene summary paragraph temporarily disappears early in exploration

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#308]
While testing #294, I noticed that the the dynamic part of the Scene Summary, the paragraph that describes the state of the sim was missing sometimes.

The disappearance happened early in my exploration, but it eventually came back. This happened twice. 

I suggest the following steps to reproduce:
1. open sims read through pdom once
2. grab book, and rub until some atoms break away
3. re-read from top with 2 finger swipe up  to check if the paragraph has disappeared.
4. play some more and read the state descriptions again to see if it came back.

I am just wondering if there is some way that parts of the PDOM could be disappearing temporarily or if this is another quirky Mobile VO issue. Perhaps it is a performance issue and VO can't read everything when performance is strained - really, I have no idea why this would happen.

Just a note, there were also a couple of times when I could not read with VO cursor swipes past a certain point. I seemed to got stuck on a heading and VO would not go any further. I think in this case the more general two-finger swipe up to read from the beginning got VO reading the state descriptions again.

**Comment by terracoda** [comment]
I am not putting blocks-sim-publication on this one because the description did come back after more interaction. I hope everyone is okay with that. Feel free to add blocking label if that is required.

**Comment by jessegreenberg** [comment]
I am pretty sure this is the same as #292, @terracoda can you confirm?

**Comment by zepumph** [comment]
Yes, I agree.

**Comment by terracoda** [comment]
I agree, too. Apologies for the duplicate issue.
