### ISSUE TITLE
Update Teacher Tips for Friction publication

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/friction#309]
As noted in https://github.com/phetsims/tambo/issues/143, the Teacher Tips doc needs the Enhanced Sounds phrasing updated to Extra Sounds. The document also needs a new screenshot that includes the Preferences menu icon.

Also, we will need to update the A11y View link in the Interactive Description section under the Inclusive Features header. To do this we provide the bayes link of the published version with the A11y view suffix. To do so, I'll need the final version number.

bayes.colorado.edu/dev/html/friction/**_1.X.X_**/phet/friction_a11y_view.html

@zepumph, can you post the publication version number here and assign back to me?

I have the doc updated, except for the link. Once I have that, I can finalize and push the update to the website.

**Comment by BLFiedler** [comment]
Updated. Files uploaded to Friction HTML5 Gdrive folder. Will push to the website when publication is finalized.

**Comment by zepumph** [comment]
Just confirming here that nothing more is needed until after the sim is published to the website. Is that correct?

**Comment by BLFiedler** [comment]
Both of these were updated on the website.
