### ISSUE TITLE
Voicing says some statements when turned off in toolbar

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#314]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/868 and possibly related to https://github.com/phetsims/ratio-and-proportion/issues/541 after turning off Voicing in the Toolbar I still hear:
1. "hide toolbar"
2. "Toolbar hidden"
3. "Toolbar shown"
4. "Close" when exiting a dialog 

This doesn't happen with published GFLB.

Also--in Ratio and Proportion in Master, I will also hear the screen name and sim title when selecting a screen from the Home Screen. Ex: "Discover Screen. Ratio and Proportion"

**Steps to reproduce**
1. In the Preferences Menu, turn on Voicing and check all Sim Voicing checkboxes
2. Turn off Voicing in the toolbar
3. Tab to the Hide Toolbar button 
4. Press the Hide Toolbar button with mouse or keyboard
5. Tab to or click on the Keyboard Shortcuts Dialog
6. Click on the Close button or press Return when the Close button has keyboard focus

**Visuals**

https://user-images.githubusercontent.com/87318828/209359864-157ef504-ecc9-47f6-be66-4a9296c729e8.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.28/phet/friction_all_phet.html?maskf
Version: 1.6.0-dev.28 2022-12-20 18:30:08 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1473x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
OK, I found why voicingVisbile wasn't working as I expected and it was an explicit choice. Serves me right for not reading documentation...

```js

    // We need an "unattached" utterance so that when the close button fires, hiding the close button, we still hear the context response.
    const contextResponseUtterance = new Utterance( {
      priority: Utterance.MEDIUM_PRIORITY
    } );
```

But this implementation will also make it impossible to prevent speaking "Close" with `voicingVisible`.

**Comment by jessegreenberg** [comment]
OK, here is my status on this issue:

1) The responses related to the toolbar are intentional when "Sim Voicing" is off. "Sim Voicing" currently turns off all Voicing for everything except the Toolbar, so we should hear voicing for the "Sim Voicing" toggle, the "Quick Info" buttons, and the toolbar push button.
2) The "Close" button case is a bug. I think it is fixed by the above commit, but it required a change to the typing in utterance-queue (https://github.com/phetsims/utterance-queue/issues/99)

@zepumph over to you to verify/review.

**Comment by zepumph** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/546 closed and thus so can this!
