### ISSUE TITLE
Assertion errors in ?fuzz test with debug version

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#315]
For https://github.com/phetsims/qa/issues/868, with macOS 13.0.1 and safari 16.1 I saw a few assertion errors when running a ?fuzz test with https://phet-dev.colorado.edu/html/friction/1.6.0-dev.28/phet/friction_all_phet_debug.html

<img width="491" alt="Screenshot 2022-12-23 at 1 19 14 PM" src="https://user-images.githubusercontent.com/87318828/209396261-ca1449e8-fd21-4505-a9de-d78025d37146.png">

Here is the detailed view:
<details>
<img width="495" alt="Screenshot 2022-12-23 at 1 18 13 PM" src="https://user-images.githubusercontent.com/87318828/209396334-87c8c21d-20ef-4c75-91c8-1702299a030c.png">
<img width="491" alt="Screenshot 2022-12-23 at 1 18 34 PM" src="https://user-images.githubusercontent.com/87318828/209396340-c6a789b7-39c5-4699-9588-a195e56680cb.png">
<img width="491" alt="Screenshot 2022-12-23 at 1 18 48 PM" src="https://user-images.githubusercontent.com/87318828/209396350-8b927fdb-7620-4759-befd-b111c77b3604.png">

</details>

**Comment by KatieWoe** [comment]
Found the steps to replicate:
1. Go to the Hatian locale
2. Try to open the Keyboard Nav dialog

![wack](https://user-images.githubusercontent.com/41024075/209397178-53bae800-5247-4b35-8755-20225f548176.png)

**Comment by KatieWoe** [comment]
This is what that translation looks like in the published version:
![onpub](https://user-images.githubusercontent.com/41024075/209397423-ca83ca59-d687-4a44-958f-465c9138cb79.png)

The "undefined" in the problem string leads me to think that is the place to look.

**Comment by KatieWoe** [comment]
I didn't see this in any other locale

**Comment by zepumph** [comment]
@marlitas and I looked into this and found that without assertions you can get this look: 

![image](https://user-images.githubusercontent.com/6856943/210635309-f232f918-33a1-4e10-aa1a-93d9c282c775.png)


It looks like we have trouble related to https://github.com/phetsims/babel/issues/18. I'll ping over there to see if we can get this fixed before publication. Noting that {{chose}} is in the "Results" in https://github.com/phetsims/babel/issues/18#issuecomment-1355853503.

**Comment by zepumph** [comment]
@oliver-phet was kicking off some builds last night and I believe it was in regards to https://github.com/phetsims/babel/issues/18. I see notes about that over in https://github.com/phetsims/rosetta/issues/329#issuecomment-1371558337. scenery-phet strings weren't done because common code strings pose extra challenges, I'll keep this issue open.

**Comment by zepumph** [comment]
Looks like all has been resolved here over in https://github.com/phetsims/babel/issues/18. Closing
