### ISSUE TITLE
Teacher Tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/friction#32]
@arouinfar Friction needs teacher tips (none are on the HTML5 sim currently).

**Comment by arouinfar** [comment]
@ariel-phet, I've started working on the tips. Do you know if there are any simplifications made to the model that need explaining? I couldn't find an associated model.md file, or any other relevant documentation.

**Comment by ariel-phet** [comment]
@arouinfar - this sim WAY pre-dates me...but I think we can infer a few things from the sim itself.

1. Moving the top book does not move the position of the bottom book (that seems like an important simplification)
2. The bottom book is assumed to be much harder than the top book (since only the top book atoms "rub off"
3. What we depict as the layer of atoms parallel to the depected edge of the book...those atoms are assumed to be tightly bound, and no amount of heat removes them.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! I will summarize these behaviors in the Model Simplifications section of the tips.

**Comment by arouinfar** [comment]
Uploaded! Closing.
