### ISSUE TITLE
Default dragging is much slower than published sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#321]
I think a lot of what was being talked about in https://github.com/phetsims/friction/issues/319 has to do with how different the dragging speed is from https://phet.colorado.edu/sims/html/friction/latest/friction_en.html. I think there was a regression for how the speed works in KeyboardDragListener.

**Comment by zepumph** [comment]
Tagging @jessegreenberg

**Comment by jessegreenberg** [comment]
Sorry about that. I can't dig in too deeply but I think https://github.com/phetsims/scenery/issues/1437 could have done this. Not entirely sure.

**Comment by zepumph** [comment]
No worries! I found values I liked that are almost identical to the published version using the new options. Closing
