### ISSUE TITLE
Assertion failed with debug sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#323]
For https://github.com/phetsims/qa/issues/886. Seen on Win 11 Chrome while running a fuzz test on the debug version of the sim. The sim froze and the error came up multiple times. It took awhile for it to manifest (~10 minutes).
<img width="468" alt="frozen" src="https://user-images.githubusercontent.com/41024075/214390657-76426126-22a9-470c-927e-726955136c4f.png">
<img width="348" alt="frozen2" src="https://user-images.githubusercontent.com/41024075/214390674-fde4d5e9-63f0-4b85-a02b-66b55241864c.png">
<img width="347" alt="frozen3" src="https://user-images.githubusercontent.com/41024075/214390688-535d021f-052e-4285-a4a1-6770f5751ead.png">

**Comment by Nancy-Salpepi** [comment]
Also seen on mac + safari/chrome

**Comment by zepumph** [comment]
Looks like it has to do with push buttons firing. This sim only has a single sim-specific push button, but that is the reset all button. So likely anything causing this is a general issue. We will keep fuzzing to figure it out more, but I would say given the challenge to reproduce (6 windows fuzzing for 5 minutes now). This isn't blocking the RC.

**Comment by zepumph** [comment]
I fuzzed 4 instances for over an hour and didn't get this to reproduce. I'm tempted to just close this issue and reopen if it comes up again. I don't see it on CT.

**Comment by jessegreenberg** [comment]
I let unbuilt version from master fuzz on Windows 10 Chrome for ~5 hours and did not see this bug.
