### ISSUE TITLE
"Released" not heard with keyboard nav

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#325]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/886, with Voicing enabled I don't hear "released" if I tab to another object, such as the Reset All button. In older dev versions such as 1.6.0-dev.23, I do hear "released" when I press Tab. 
I still hear "released" when I let go of the book with my mouse. 

**Steps to reproduce**
1. Turn on Voicing
2. Use keyboard nav to grab chemistry book
3. Press tab

**Visuals**

https://user-images.githubusercontent.com/87318828/214592186-56db03ad-e824-45ee-8138-690bb906da8f.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet/friction_all_phet.html?printVoicingResponses
Version: 1.6.0-rc.1 2023-01-17 16:32:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
One way to fix this is to increase the priority of the `releasedUtterance` in GrabDragInteraction. The name response that is spoken on focus is just cancelling the `released` Utterance.

**Comment by Nancy-Salpepi** [comment]
With VoiceOver, when I tab to the Reset All button, I first hear "Reset All button" and then I hear "Released," which I think is a bit confusing. 

https://user-images.githubusercontent.com/87318828/215540879-61b53096-f742-4b4e-aab4-ab50f189d79d.mov

**Comment by zepumph** [comment]
It would be most efficient if @jessegreenberg and or I worked on this one for the timing tweaks.

**Comment by zepumph** [comment]
I didn't get to this today, @jessegreenberg I'll try for tomorrow

**Comment by samreid** [comment]
@zepumph and I increased the priority and confirmed the behavior is good.  The increased priority also made it so the releaseUtterance interrupts text like `Grabbed. Lightly on Physics book.` and also the object responses like `Atoms jiggle a tiny bit, temperature cool.` but we agreed that is for the best, since the user has moved to something else.  Therefore, we removed the cancelOther: false (which was added in https://github.com/phetsims/friction/issues/212#issuecomment-901501404)

This issue is ready to cherry-pick 2 commits.

**Comment by jessegreenberg** [comment]
`cherry-pick`ed the two commits, and tested in RC SHAs. Ready to verify.

**Comment by pixelzoom** [comment]
@jessegreenberg You added ready-for-review, but no assignee to review. So assigning to you.

**Comment by Nancy-Salpepi** [comment]
Sounds good in rc.3. Closing.
