### ISSUE TITLE
Quick info alerts interrupted with Chrome 109

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#327]
For cherry picking https://github.com/phetsims/joist/issues/898 into the rc branch

**Comment by jessegreenberg** [comment]
Here is the commit to cherry-pick: https://github.com/phetsims/utterance-queue/commit/2f64e9580771087750bdc3f1c5ac778abb089f1f

**Comment by jessegreenberg** [comment]
Before cherry-picking, I tried to reproduce the problem in current friction-1.6 SHAs and could not. I tried to reproduce it in rc.1 and could not. But I DO see it in dev.38.

I see https://github.com/phetsims/utterance-queue/commit/2f64e9580771087750bdc3f1c5ac778abb089f1f already in friction-1.6 SHAs. I don't know how it could have been in friciton-1.6, but believe it is already fixed.

**Comment by pixelzoom** [comment]
@jessegreenberg Who added ready-for-review, but no assignee to review. So assigning to you.

**Comment by jessegreenberg** [comment]
This is in the QA process and is being reviewed in in the next RC.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3. Closing.
