### ISSUE TITLE
Responsive Description sometimes stops

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#331]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
Safari 16.2

**Problem description**
For https://github.com/phetsims/qa/issues/886, after playing with the sim for several minutes, I sometimes no longer see alerts in a11y view or hear then with VO. Tabbing away from book or pressing Reset All button does not fix the problem. 

This has happened 3-4 times, but I can't pinpoint the steps to reproduce it at this point and I don't know if it occurs outside Safari as of now. 

**Steps to reproduce**
still trying to figure them out

**Visuals**
This video is long but I wanted to include what was happening before responsive description stopped.
https://user-images.githubusercontent.com/87318828/215544500-1828834b-9a30-4342-af68-41d78cecfb5b.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet/friction_all_phet.html
Version: 1.6.0-rc.1 2023-01-17 16:32:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi what alerts specifically are you not seeing in the a11y-view? All of them or ones that are specific to this sim?

**Comment by Nancy-Salpepi** [comment]
I would say all alerts because I don't even hear the one after pressing Reset All. 

In the video, after I stopped seeing alerts in the yellow box when moving the book, I tabbed to and pressed the Reset All button, but "Sim Screen Restarted. Everything Reset." didn't appear in a11y view.

**Comment by jessegreenberg** [comment]
Ah, thanks - I see that now. Not seeing the alerts in the a11y view means it is a problem in PhET code and likely not platform specific. Are you able to see this in Chrome?

**Comment by Nancy-Salpepi** [comment]
Trying to replicate on Chrome now.
I will also tab around more the next time it happens to see if anything is read (but I don't think anything was).

**Comment by Nancy-Salpepi** [comment]
After clearing history, it happened almost immediately in Chrome. Definitely not sim-specific. I didn't see "audio features on/off" or "highlights on for all input" in a11y view.

**Comment by jessegreenberg** [comment]
Great, thanks @Nancy-Salpepi. We will take a look then.

**Comment by zepumph** [comment]
@jessegreenberg and @Nancy-Salpepi and I met and were able to reproduce this! It was an incredibly tiny but powerful bug given a case involving Utterance.predicate being false only just before announcing to aria-live. Fixed in 

https://github.com/phetsims/utterance-queue/issues/101.

Please cherry pick https://github.com/phetsims/utterance-queue/commit/9e7c5bb60be20c882d83995f7fe32efee8f4526a

**Comment by jessegreenberg** [comment]
Cherry-pick referenced above. I did not try to reproduce this bug, but verified basic Voicing functions in 1.6 SHAs. Ready to verify in next RC.

**Comment by Nancy-Salpepi** [comment]
In rc.3 I was unable to reproduce this issue after 10 minutes. Closing, but will reopen if needed.
