### ISSUE TITLE
Examples.md has a typo in a `phetioID`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/friction#332]
For https://github.com/phetsims/qa/issues/886.

@stemilymill found a typo in the examples doc. There's a `phetioID` that currently begins with `iction` instead of `friction`. There isn't currently any validation for the `phetioIDs` shared in client documentation, but it's a feature we've considered in https://github.com/phetsims/phet-io-sim-specific/issues/21.

@zepumph I'll take care of the typo in master and then pass it over to you for cherry-picking.

**Comment by arouinfar** [comment]
Fix committed and referenced above, ready for cherry-picking @zepumph.

**Comment by jessegreenberg** [comment]
Cherry-pick into 1.6 SHAs done. I don't know how to test this change and will lean on QA to verify.

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.3. Closing.
