### ISSUE TITLE
Loading Studio with some nonexistent locales results in assertion error

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#334]
For https://github.com/phetsims/qa/issues/886, noting that the bug reported in https://github.com/phetsims/beers-law-lab/issues/320 also happens with Friction.

**Comment by jessegreenberg** [comment]
cherry-pick done, and I confirmed that the bug described in https://github.com/phetsims/beers-law-lab/issues/320 is no longer happening with 1.6 SHAs. Ready to verify.

**Comment by KatieWoe** [comment]
Looks good in rc.3
