### ISSUE TITLE
Voicing reads Arrows in wrong order in dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#337]
**Test device**
Mac

**Operating System**
10.15.7 and 13.1

**Browser**
safari/chrome

**Problem description**
For https://github.com/phetsims/qa/issues/886, this is minor: In the keyboard shortcuts dialog, Voicing reads the arrows in the wrong order. The arrows look like this:
<img width="129" alt="Screenshot 2023-02-03 at 8 02 10 AM" src="https://user-images.githubusercontent.com/87318828/216610111-58509d04-b676-4000-9b00-7588746553dd.png">

but Voicing reads them as "Up. Left. Down. Right.

This also happens in Quadrilateral.

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet/friction_all_phet.html
Version: 1.6.0-rc.1 2023-01-17 16:32:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1600x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
@terracoda and I reviewed this and found that the icons were accidentally reordered in [c5be548ed9fd3dae61381331f9aa63fd68352e1e, I will ](https://github.com/phetsims/scenery-phet/commit/c5be548ed9fd3dae61381331f9aa63fd68352e1e), Ill change the order in scenery-phet.

**Comment by jessegreenberg** [comment]
OK, reverted the order to what it once was. @terracoda said that this order was important because it matches the movement of the WASD keys. Great catch @Nancy-Salpepi!

![image](https://user-images.githubusercontent.com/6396244/216693294-8361a4c9-43e3-49b8-b682-13434a5bfb45.png)

**Comment by jessegreenberg** [comment]
cherry-picked, ready to verify.

**Comment by KatieWoe** [comment]
Looks good in rc.3
