### ISSUE TITLE
Muting sound through preferences is not stateful

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#338]
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
From https://github.com/phetsims/qa/issues/886
> Some preference selections are saved into the simulation state, and persist in the save and launch process of the Standard PhET-iO Wrapper. These include audioEnabledProperty, colorProfileProperty, and all settings on the Simulation tab.

However, if you use the preferences menu to disable sounds, this is not carried over in state. The audio features toggle is and so is the nav bar button.

**Visuals**
<img width="419" alt="soundsoff" src="https://user-images.githubusercontent.com/41024075/216715789-3ffa7ce3-f321-442f-b5cc-72a607236fb5.png">

**Comment by arouinfar** [comment]
@KatieWoe the only stateful property related to audio is `general.view.audioManager.audioEnabledProperty` which is hooked up to the "Audio Features" toggle and the Audio Toggle button in the navbar. The Sound toggle in the Preferences dialog is powered by a different property, `general.view.soundManager.enabledProperty` which is not intended to be stateful. Closing.
