### ISSUE TITLE
Atoms not captured by screenshot

### ISSUE THREAD

**Issue by phet-steele** [phetsims/friction#35]
The screenshot feature from the PhET menu.
![-friction- screenshot 1](https://cloud.githubusercontent.com/assets/5863899/17440999/4eeae1b0-5aec-11e6-873e-eff04f0b7580.png)

**Comment by jbphet** [comment]
Interesting.  I think this is probably because this sim using something like a CanvasNode, but was likely done before the actual CanvasNode existed.  I'll take a look and see if there is a reasonably quick fix and, if not, I'll just disable the feature and get to it later.

**Comment by jbphet** [comment]
I just tested this on master, and the atoms are still not captured in the screenshot, so the problem is deeper than just having an outdated version of Scenery.

**Comment by jbphet** [comment]
I just took a quick look at the Friction code, and the work to be done would be to make AtomCanvas inherit from CanvasNode and implement the methods necessary to draw the atoms.  I'm estimating two or three hours of focused work to get this done.

**Comment by jbphet** [comment]
An RC is now out with a fix for this, but the testing of it is apparently low priority.  The ticket is https://github.com/phetsims/tasks/issues/698.  This will be on hold until testing is complete.

**Comment by phet-steele** [comment]
Fixed, closing.
