### ISSUE TITLE
Book can get stuck moving in one direction after keyboard dragging

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#39]
From #38 @zepumph said
>if you are moving either object to the right, and then tab away, it gets stuck going to the right, and the behavior is very strange.

It sounds like the key state object in the drag handler isn't getting reset after it loses focus. @zepumph could you please try adding something like this in the constructor of KeyboardDragHandler?

```js
    // @public (read-only) - listener that will be added to the node so that when focus is lost, the keystate is
    // reset and dragging stops
    this.blur = function( event ) {
      self.reset();
    }
```

we are probably doing something like this manually in BASE (could be removed once this is added).

**Comment by zepumph** [comment]
@jessegreenberg how does that look (my comment isn't as good)?  Back to you to review, and remove logic in BASE as needed.

**Comment by jessegreenberg** [comment]
Looking great @zepumph, thanks, I removed the explicit reset in BASE since this fixed the general issue. Closing.
