### ISSUE TITLE
Should you be able to click and drag the yellow book outside the magnifying view?

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#40]
From an accessibility meeting today, @ariel-phet mentioned that it isn't good that you can start a drag from the white space above/to either side of the magnified view (see the highlighted area below for an example)

![image](https://user-images.githubusercontent.com/6856943/30604637-0f5e2e70-9d18-11e7-9254-c9fef6f600c2.png)

@ariel-phet is this something that we should cover as we are in this sim for a11y anyways?

**Comment by ariel-phet** [comment]
I think it is a bit odd, but I think it can be left as is since it doesn't not cause any usability issues.
