### ISSUE TITLE
keyboard navigation works for some items, not others in Safari

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/friction#51]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS High Sierra 10.13.1 (17B1003)

**Browser:**

Safari Version 11.0.1 (13604.3.5)

**Problem description:**

In Safari, you can only tab through the chemistry textbook, the closeup of the chemistry textbook, and the URL. You can't tab through the reset button, the keyboard nav menu, or the PhET menu. This is for phetsims/QA/issues/75.

EDIT: In resistance in a wire, the only item you can tab through is the URL.

**Steps to reproduce:**

1. Open sim in Safari.
2. Hit tab several times.

**Screenshots:**

![tomato](https://user-images.githubusercontent.com/31285590/33636425-446944a8-d9d9-11e7-8866-2f12df4839b1.gif)

**Troubleshooting information (do not edit):**

Name: ‪Friction‬
URL: https://www.colorado.edu/physics/phet/dev/html/friction/1.4.0-rc.2/friction_en.html
Version: 1.4.0-rc.2 2017-12-05 18:19:27 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Language: en-US
Window: 1440x700
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d70f5056","branch":"HEAD"},"babel":{"sha":"26366701","branch":"master"},"brand":{"sha":"53cf227b","branch":"HEAD"},"chipper":{"sha":"6f8b4c13","branch":"HEAD"},"dot":{"sha":"f09e44aa","branch":"HEAD"},"friction":{"sha":"d2fa6e36","branch":"HEAD"},"joist":{"sha":"bc8f433b","branch":"HEAD"},"kite":{"sha":"72dcc8ee","branch":"HEAD"},"phet-core":{"sha":"88a51822","branch":"HEAD"},"phetcommon":{"sha":"f0288123","branch":"HEAD"},"query-string-machine":{"sha":"b8bdcc28","branch":"HEAD"},"scenery":{"sha":"31c7d26f","branch":"HEAD"},"scenery-phet":{"sha":"594695db","branch":"HEAD"},"sherpa":{"sha":"0f5f30f7","branch":"HEAD"},"sun":{"sha":"2d4b1ff7","branch":"HEAD"},"tandem":{"sha":"56c77424","branch":"HEAD"}}

**Comment by lmulhall-phet** [comment]
It's a Safari preferences issue. Closing.

**Comment by zepumph** [comment]
Could someone list the preferences that caused/fixed this just in case it comes up again?

**Comment by lmulhall-phet** [comment]
Safari > Preferences > Advanced > Press Tab to highlight each item on a webpage

**Comment by zepumph** [comment]
Thanks!
