### ISSUE TITLE
Sim doesn't load for LoL in Edge

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#55]
In #53 @BryceAG said

>Also in Edge it doesn't load for LOL

For https://github.com/phetsims/QA/issues/75.

**Comment by jessegreenberg** [comment]
RIAW seems to load fine in LoL in Edge so this is a problem with Friction or with these SHAs https://www.colorado.edu/physics/phet/dev/html/friction/1.4.0-rc.2/dependencies.json

**Comment by jessegreenberg** [comment]
Now it is loading fine in LoL for me. @BryceAG, or @phet-steele could you please verify? If it is still a problem, @BryceAG could you provide additional platform details?

**Comment by jessegreenberg** [comment]
@zepumph would you be able to verify this as well since you develop on Windows?

**Comment by zepumph** [comment]
@jessegreenberg steps to verify please? I have never tested lol.

**Comment by jessegreenberg** [comment]
Can be tested by navigating here:
http://harness.legendsoflearning.com/

In the "Game URL" field, put the sim url, which can be from localhost, and add query parameter `?legendsOfLearning`.

"Learning Objectives" select box can be ignored.

Press "Test It"

Sim should load in an iframe with buttons on the right.

**Comment by zepumph** [comment]
Seems to work to me!

**Comment by phet-steele** [comment]
Loads fine on our Edge QA devices. Closing.
