### ISSUE TITLE
Edge Performance

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#58]
In #54 @BryceAG said
>Also the keyboard nav that does work is very delayed, taking about half a second before the book actually moves.

@BryceAG discovered that this is true when the temperature is high and the atoms are moving quickly, so this is a performance problem.

At high temperature I tried to move the book with a mouse and observed similar delays, so this is a general Edge performance problem and not specific to a11y.

@ariel-phet @emily-phet should we investigate performance in Edge now or mark as deferred/wontfix? Whoever works on this would want to touch base with @jbphet for this since he is listed as responsible dev.

**Comment by jessegreenberg** [comment]
In my opinion, performance with a mouse in Edge is equivalent to the current public version on the site, so we are not degrading performance in this version.

**Comment by jessegreenberg** [comment]
For phetsims/QA#75.

**Comment by emily-phet** [comment]
@jessegreenberg Agreed - if the behavior with the mouse interaction in the published version is similar to the keyboard interaction, I don't think this needs to be addressed.

**Comment by ariel-phet** [comment]
@jessegreenberg playing with edge on my laptop with the published version I saw no performance problems.

Checking the RC version I also saw no performance issues with mouse or with keyboard. 

I think this issue can be closed.
