### ISSUE TITLE
Bad LICENSE in several sims

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#69]
![image](https://user-images.githubusercontent.com/679486/36174749-802ef5a0-10ca-11e8-9009-62d822d47747.png)

build-an-atom referenced in wrong sims.  Discovered in #64

**Comment by samreid** [comment]
It looks like the majority of the LICENSE files were committed by @jbphet, reassigning it to @jbphet so he knows its a problem and to address it.  I think we just use the GPL v3 template (without filling in the project name).

**Comment by jbphet** [comment]
Yes, it appears that the template portion was filled in for these files.  The line in question should look like this:
```
{project}  Copyright (C) {year}  {fullname}
```

**Comment by jbphet** [comment]
Should be fixed, closing.  @samreid - feel free to take a look if you'd like to double check, and re-open if necessary.
