### ISSUE TITLE
Re-testing after review/maintenance complete

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#72]
After we decide what to do with #71 and #70, this simulation needs at least a dev test to make sure the multitude of recent commits haven't been detrimental.  On hold until we decide what do do with #71 and #70.

**Comment by jbphet** [comment]
I addressed #70 and #71 and set up a dev test by QA (see https://github.com/phetsims/QA/issues/127) and the sim passed the testing.  I think it's safe to close this now.
