### ISSUE TITLE
Assertion due to uninstrumented focasable instance

### ISSUE THREAD

**Issue by jbphet** [phetsims/friction#82]
There was a report in https://github.com/phetsims/phet-io-wrapper-sonification/issues/57#issuecomment-405309259 that some of the keyboard navigation isn't working in one of the sonification wrappers.  I just tried testing this navigation on a RequireJS phet-io version of the sim, and hit an assertion.  The message is:

```
Assertion failed: When running phet-io mode, all focusable instances must be instrumented.
```

The stack trace is:
```
window.assertions.assertFunction (assert.js:22)
set focus (Display.js?bust=1531764189510:1772)
onFocus (AccessiblePeer.js?bust=1531764189510:139)
```

This can be duplicated on the current master by loading phetmarks, selecting the friction sim, selecting the "active" mode, pressing the "Launch" button, and using the tab key to move through the possible selections.

Assigning to @zepumph because, well, because he asked for it.  This is high priority because it's blocking sonification/issues/57.

**Comment by jbphet** [comment]
@zepumph - please assign this back to me once it's fixed to help me remember to republish the sonification wrappers.

**Comment by zepumph** [comment]
@jbphet please see if it is fixed now. 

@samreid I moved the instrumentation from the type to the sub node that gets focus. I'm not sure this is the best for all cases, but we can revisit this when we thoughtfully design friction. Notice how it is a bit weird in `MagnifierNode` to have the `magnifiedNode` be a sibling of dragHandlers that are technically "children" in regards to the tandem structure.

**Comment by samreid** [comment]
I agree with everything in the preceding comment--this should work for now.

**Comment by jbphet** [comment]
I've tested this out and the behavior now looks correct, and others have verified that it works correctly in the latest deployed sonification wrappers (see https://github.com/phetsims/phet-io-wrapper-sonification/issues/57#issuecomment-405669807).  Thanks for the quick fix!  Closing.
