### ISSUE TITLE
Only need one copy of how to move book help text in PDOM

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#87]
There are 2 copies of the help text paragraph describing how to move the book and zoomed-in book.

> Arrow keys, or letter keys W, A, S, or D move book up, left, down, or right.

Please remove the second one, and in addition my initial text sounds a bit odd to me, so please change the remaining first instance of the help text to,
"Use arrow keys, or letter keys W, A, S, or D to move book or zoomed-in book up, left, down, or right."

Note: I changed issue to keep first and remove second instance of help text.

**Comment by terracoda** [comment]
I took care of the string update in commit 3d32df0, but I don't know how (and likely shouldn't try) to remove one instance of the help text from the PDOM.

I'll wait for someone else to take care of removing the first instance.

**Comment by terracoda** [comment]
Actually, lets try leaving the fist instance and removing the second instance instead. Sorry for the confusion.

**Comment by jessegreenberg** [comment]
Removed the duplicate content and verified with @terracoda that this is correct. Closing.
