### ISSUE TITLE
Add "surface temperature" to "thermometer" in screen summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#88]
To eventually shorten alerts, it might be useful to provide more set-up details in the screen summary, so I will try to add "surface temperature" before "thermometer" in screen summary.

Example paragraph from design doc - adding bolded text and removed "at" before "cool":

> Chemistry book rests on top of a Physics book, and is ready to be rubbed against it. In a  zoomed-in view of where books meet, atoms {{jiggle a tiny bit}}, and {{**surface temperature** thermometer is cool}}. {{Move Chemistry book to rub books together}}.

**Comment by jessegreenberg** [comment]
Fixed in the above commit.
