### ISSUE TITLE
Friction description & alerts round 2

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#90]
In issue #81, @zepumph did a great job implementing most of the descriptions and alerts for Friction.

After testing with VoiceOver, I found that the jiggle/temperature alerts were too long and that we should consider options for how to time the firing of these alerts so they do not pile up in the utterance queue. 

Additionally, @emily-phet and I decided it would likely be better to describe changing temperature information rather than actual temperature information for this sim's experience.

@zepumph, we should meet asap to discuss changes in the [Friction A11y Design Main](https://docs.google.com/document/d/1v7GM_dNZs86jcRn2X03D2t7HFDb4dQ1h4ayDGXTu63U/edit#) document.

**Comment by terracoda** [comment]
@terracoda to create smaller issues and point to the design document where necessary.

**Comment by terracoda** [comment]
@zepumph, as discussed I created several issues regarding round 2 descriptions, small and some more complex.
- [ ] #91 
- [ ] #92 
- [ ] #93 
- [ ] #94 
- [ ] #95 

Comment in issues if you have concerns or questions.

**Comment by zepumph** [comment]
@terracoda here is the newest sonification wrapper with updated descriptions from work today. 

https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.73/phet-io-wrapper-sonification/friction/html/friction-sonification.html?sonificationFile=sonificationDefault&accessibility

**Comment by zepumph** [comment]
new round of issues has been created from feedback given during a meeting today from @terracoda. I'm going to close this issue, and we can make new ones from here.
