### ISSUE TITLE
Change "Control Panel" to "Control Area"

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#91]
@zepumph here's a tiny issue ;-) 
Please change "Control Panel" to "Control Area" when you get a chance.
By the way where does this string live? I couldn't find it.

**Comment by terracoda** [comment]
No rush ;-)

**Comment by zepumph** [comment]
I hope this will be covered by a robust solution in https://github.com/phetsims/scenery-phet/issues/381, unassigning, but don't worry it is still on my raday.

**Comment by zepumph** [comment]
Changed occurred with https://github.com/phetsims/scenery-phet/issues/397, I don't think we need to wait for the decision in https://github.com/phetsims/scenery-phet/issues/381 to proceed with this. 

@terracoda said:
>By the way where does this string live? I couldn't find it.

It is factored out into a common type in scenery-phet: https://github.com/phetsims/scenery-phet/blob/master/js/SceneryPhetA11yStrings.js#L40

and then used by `scenery-phet/js/accessibility/nodes/ControlAreaNode.js`

Over to @terracoda to review and close if all is good.

**Comment by terracoda** [comment]
I hear "Control Area" now, and thanks for the explanation of where to find it. 

FYI, we are considering removing the Control Are for "simple sims" (see https://github.com/phetsims/john-travoltage/issues/295), but I will open a new issue for that if/when that happens.

"Control Area" sounds good for now, so closing this issue.
