### ISSUE TITLE
Not hearing "Chemistry book" or "Zoomed-in Chemistry book" on auto read through

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#92]
In Safari with Voice Over, I do not hear the names of the custom interactive objects when I read automatically from beginning of sim with VO's **Control-Command-B** read-from-beginning shortcut.

If I use the cursor keys I hear both, but just not with the read-from-beginning command.

I think the problem is that the object is an empty div with an aria-label. We may need to explore different options for the HTML to represent this object.

**Question:**
1. Does this happen with JAWS or NVDA? 

I checked it in ChromeVox & Chrome and objects are reads out fine. All content is read out when reading the PDOM from the top with ChromeVox.

**Comment by terracoda** [comment]
@zepumph, are you able to test with NVDA? If not, I check in with QA or @jessegreenberg. 

Not a high priority at the moment.

**Comment by terracoda** [comment]
@zepumph, on NVDA, I would guess that you would hear, "Chemistry book, web application" on focus of the interactive book. 

Only VoiceOver supports aria-role description at this time, which is indeed unfortunate.

Looks like an empty div with a label is only a problem for VoiceOver. I think we can leave this for now, and I'll just double check labeling techniques for elements with role application.

**Comment by zepumph** [comment]
I think I misunderstood this issue. I see now, that as I let NVDA read through everything in the PDOM at once, or as I use the down arrow keys for one line at a time, the divs with application "role" are skipped. I wonder if this has to do with https://github.com/phetsims/a11y-research/issues/116

**Comment by terracoda** [comment]
@zepumph, so NVDA is also skipping the aria-labeled-empty `div`s when you read through the PDOM by paragraph and even if you read or step through with the cursor keys?

I do think the element is getting skipped because the `div`s are empty.

I have not investigated the following possibilities, but here are a few non-empty options:
``` html
<div role="application" aria-roledescription="Chemistry book, move in 4 directions" aria-label="Chemistry book">Chemistry book</div>
```

What happens if you another element and `aria-labelledby` instead of `aria-label`:
``` html
<div role="application" aria-roledescription="Chemistry book, move on 4 directions" aria-labelledby="book-label">
<div id="book-label">Chemistry book</div>
</div>
```
I'm not sure an `h3` is the right element, but you could also try something similar with a heading element, again with or without `aria-labelledby`: 

``` html
<div role="application" aria-roledescription="Chemistry book, move on 4 directions" aria-labelledby="book-label">
<h3 id="book-label">Chemistry book</h3>
</div>
```

**Comment by terracoda** [comment]
I am not 100% sure the above examples are valid code, but nothing immediately jumps out as terribly incorrect.

**Comment by zepumph** [comment]
I went with the first sample you gave, where the innerContent of the div, and the ariaLabel, are both set to the title, and it works great! At least as far as my inexperienced screen reader skillz can tell. Committed above, please let me know what you think.

**Comment by zepumph** [comment]
Discussed as part of the A11y meetings today. We are good to proceed with the current strategy. Closing. @terracoda please reopen if you feel differently.
