### ISSUE TITLE
Change threshold, affecting second break away alert

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#95]
@zepumph, I would like to always hear "Atoms break away..." on the first break away, and then on all subsequent break-aways, hear "More atoms break away."

Is that possible?

**Comment by zepumph** [comment]
Much of the original work to convert the break away alerts was done as part of the first commits in  #94, but the above commit cleaned it up, and got things working with the reset all button as well. @terracoda please review what you think when you get back.

**Comment by terracoda** [comment]
@zepumph, this seems to working nicely now. I always here the first breakaway, "Very hot.Atoms break away..." first and then the second breakaway "Very hot. More atoms break away." second.

**Comment by terracoda** [comment]
I think it is ok to close this issue.
