### ISSUE TITLE
Increasing the "decreasing" threshold to get less cooling alerts

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#99]
From a meeting today, it would be good to increase the threshold definition of "decreasing" so that the first cooling alert occurs later than it is now.

**Comment by zepumph** [comment]
I just doubled the threshold, and I'm curious what @terracoda thinks now. 

To give some perspective, the starting amplitude is 1, the evaporation amplitude is 7, and I just increased the threshold from .5 to 1. Let me know what you think @terracoda.

**Comment by terracoda** [comment]
@zepumph, I am getting fewer cooling alerts and the faster-warmer alerts fire nicely and do not get interrupted a a small slow down. 

I never hear a gradual increase. When friction is increasing, I hear one or more of "Jiggling faster, warmer" and then a breakaway, "Very hot. ..."

This might be fine as things happen so fast when user is actively increasing friction, and then the user gets a more gradual described experience of the decrease of the friction when they actually stop interacting.

It would be nice to get one instance of "Faster, now hotter" or "Faster, hotter" if possible, but I am not sure how to do it. 

Could you do it based on a percentage of increased velocity/temperature from the time of the last "Jiggling more, warmer" alert fired?

**Comment by terracoda** [comment]
@zepumph, assigning back to you after my review.

**Comment by terracoda** [comment]
We can discuss options for this as well.

**Comment by terracoda** [comment]
@zepumph, I just noticed that if I just increase friction a little, I don't seem to get "Jiggling more, warmer". I actually have to do a lot of friction before getting a warming alert. Did you change the threshold for both cooling and warning? 

We can find time to discuss on Friday.

**Comment by zepumph** [comment]
This issue will be covered by #106, because I will add a query parameter to adjust the time in between cooling alerts. Closing.
